HoudiniGraphql/houdini

packages/houdini-common/src/graphql.ts
packages/houdini-compiler/src/compile.ts
packages/houdini-compiler/src/generators/artifacts.test.ts
packages/houdini-compiler/src/generators/artifacts.ts
packages/houdini-compiler/src/testUtils.ts
packages/houdini-compiler/src/types.ts
packages/houdini-preprocess/src/utils/walkTaggedDocuments.ts

Detect document changes in preprocessor

---

.gitignore
example/.gitignore
example/houdini.config.cjs
example/src/routes/_layout.svelte
packages/houdini-common/src/config.ts
packages/houdini/src/generators/runtime/index.ts
packages/houdini/src/generators/runtime/template/mutation.ts
packages/houdini/src/validators/typeCheck.test.ts
packages/houdini/src/validators/typeCheck.ts
packages/houdini/tsconfig.json

This PR fixes #38 and adds logic to the connection validator that verifies the fragments and directives point to known connections

Better document validation

---

packages/houdini-common/src/parse.test.ts
packages/houdini-common/src/parse.ts

This PR is a continuation of #74 to add some tests

fixes single-quoted attribute values not being parsed

---

packages/houdini/cmd/init.ts

This adds a new option to the init command to specify where the schema file should be written to.

Add schemaPath option to init command

---

packages/houdini/cmd/generators/typescript.test.ts
packages/houdini/cmd/generators/typescript.ts

Fix mutation input types

---

CONTRIBUTING.md
README.md
example/src/routes/[filter].svelte
packages/houdini-common/src/config.ts
packages/houdini/cmd/generate.ts
packages/houdini/cmd/generators/artifacts/artifacts.test.ts
packages/houdini/cmd/generators/artifacts/index.ts
packages/houdini/cmd/generators/artifacts/operations.ts
packages/houdini/cmd/generators/artifacts/selection.ts
packages/houdini/cmd/transforms/index.ts
packages/houdini/cmd/transforms/list.ts
packages/houdini/cmd/transforms/lists.test.ts
packages/houdini/cmd/transforms/schema.test.ts
packages/houdini/cmd/transforms/schema.ts
packages/houdini/cmd/validators/typeCheck.test.ts
packages/houdini/cmd/validators/typeCheck.ts
packages/houdini/runtime/cache/cache.test.ts
packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/list.ts
packages/houdini/runtime/cache/record.ts
packages/houdini/runtime/scalars.test.ts
packages/houdini/runtime/types.ts

This PR starts the work for #55 by renaming `@connection` to `@list`

renamed @connection to @list

---

packages/houdini/runtime/cache/cache.test.ts
packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/record.ts
packages/houdini/runtime/types.ts

This PR fixes #131 by improving the behavior of the cache in light of null links (either records or list of records)

Better behavior for null values in cache

---

example/package.json
lerna.json
packages/houdini-preprocess/package.json
packages/houdini/cmd/generators/runtime/copyRuntime.ts
packages/houdini/cmd/generators/runtime/indexFile.ts
packages/houdini/package-lock.json
packages/houdini/package.json

This PR fixes the path generation when stamping out a few files in order to address some issues in houdini's compatibility with windows

Fix windows compatibility 

---

.gitignore
package.json
packages/houdini/package.json

This PR closes #138 and adds meta data to the `houdini` package so that the project's page provides something useful

add npm project meta info

---

README.md
packages/houdini-common/src/config.ts
packages/houdini-common/src/graphql.ts
packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts
packages/houdini/cmd/generate.ts
packages/houdini/cmd/generators/artifacts/artifacts.test.ts
packages/houdini/cmd/generators/artifacts/index.ts
packages/houdini/cmd/generators/artifacts/pagination.test.ts
packages/houdini/cmd/generators/index.ts
packages/houdini/cmd/generators/persisted-queries/index.ts
packages/houdini/cmd/main.ts
packages/houdini/cmd/transforms/fragmentVariables.test.ts
packages/houdini/cmd/transforms/paginate.test.ts
packages/houdini/runtime/network.ts
yarn.lock

I've gone ahead and wrote some docs. Feel free to adjust them however you like or i can do it too. 
I tested the apollo style in the example and it works smoothly. 
Closes #93

Feat: Persisted Queries

---

CONTRIBUTING.md
example/package.json
yarn.lock

Was thinking that this would be a nice little quality of life improvement for contributors.

Update yarn dev command in example project to run both web & api servers

---

packages/houdini/runtime/scalars.test.ts
packages/houdini/runtime/scalars.ts

recently I ran into a houdini behaviour that felt conter intuitive to me.
with a schema as such:
```graphql
type MyData {
dates: [DateTime]
}
```
and houdini config:
```js
export default {
// ...
scalars: {
DateTime: {
type: 'Date',
unmarshal(val) {
return new Date(val)
},
marshal(date) {
return date.getTime()
},
},
},
}
```
I would get `undefined` related errors trying to work with my `dates` array.
Turns out that the `unmarshal` function is being passed an array and not single values.
Given that the array structure is already unmarshal'ed as it's part of the json format, seems irrelevant to pass it in.
So here is a change to only pass the individual scalars to the marshal functions.
This keeps those methods smaller and more focused
wrote pretty naively, let me know if there is a better …

fix marshalling lists of scalars

---

packages/houdini/runtime/network.ts

https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next172
this file has no tests so please 👀

rename load's 'context' to 'stuff' following change in sveltekit

---

.changeset/beige-emus-promise.md
packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts

I suppose this happened during the partial data thing

Give `afterLoad` the real data

---

.changeset/lucky-poems-notice.md
src/runtime/cache/cache.ts
src/runtime/cache/lists.ts
src/runtime/cache/storage.ts
src/runtime/cache/tests/list.test.ts
src/runtime/cache/tests/storage.test.ts

This PR fixes a few edge cases I ran into while trying to break things.

Remove then insert

---

.changeset/slimy-eyes-cheat.md
package.json
yarn.lock

Well updating the svelte dependency fixed it...

Allow using `@const` (and probably other new features)

---

integration/api/graphql.mjs
integration/api/schema.graphql
integration/src/app.d.ts
integration/src/app.html
integration/src/hooks.ts
integration/src/lib/graphql/houdiniClient.ts
integration/src/lib/graphql/operations/QUERY.Session.gql
integration/src/lib/utils/routes.ts
integration/src/lib/utils/testsHelper.ts
integration/src/routes/__error.svelte
integration/src/routes/__layout.svelte
integration/src/routes/preprocess/query/scalars.spec.ts
integration/src/routes/preprocess/query/simple.spec.ts
integration/src/routes/preprocess/query/variable/[id].spec.ts
integration/src/routes/stores/network-session.spec.ts
integration/src/routes/stores/network-session.svelte
integration/src/routes/stores/network.spec.ts
integration/src/routes/stores/network.svelte
integration/src/routes/stores/ssr-[userId].spec.ts
integration/src/routes/stores/ssr-session.spec.ts
integration/src/routes/stores/ssr-session.svelte
src/cmd/init.ts
src/runtime/adapter.ts
src/runtime/cache/cache.ts
src/runtime/lib/context.ts
src/runtime/lib/network.ts
src/runtime/lib/pagination.ts
src/runtime/lib/types.ts
src/runtime/stores/query.ts

FIX: session (SSR / Network / preprocess)

---

.changeset/ninety-roses-double.md
src/cmd/generators/typescript/inlineType.ts
src/cmd/generators/typescript/typescript.test.ts

This PR fixes an error in the type generation when mixing interfaces on interfaces. 
closes #352

Fix type generation with interfaces on interfaces

---

.changeset/long-donkeys-travel.md
package.json

export preprocessor types

---

.changeset/soft-garlics-glow.md
src/cmd/generators/runtime/adapter.ts
src/runtime/adapter.ts
src/runtime/lib/network.ts
yarn.lock

This PR fixes an issue when retrieving the session while prerendering the app. #405 did the actual bulk of the work here avoiding the error when prerender is set to true so all we needed to do here is resurface the error if we detect that session is being used in a network function
fixes #400

fix session retrieval when prerendering

---

.changeset/cuddly-spoons-lick.md
.changeset/giant-houses-invent.md
src/cmd/generators/typescript/index.ts
src/cmd/generators/typescript/typescript.test.ts
src/cmd/utils/flattenSelections.ts
src/runtime/stores/subscription.ts

fixed bug when generating list operation types without masking

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md
.prettierignore

To go to 💯% on https://github.com/HoudiniGraphql/houdini/community
- 3 flows for "New Issue"
- Bug Report _(Not putting too many constraints on reporting a bug)_
- Feature Request
- New Discussion
- `CONTRIBUTING` guide redirecting to the appropriated section in the doc
- `pull_request_template` to have something
Let me know 👍

:sparkles: IMPROVE: Community Standards

---

site/src/routes/index.svelte
site/src/routes/intro/pagination.svx

Just fixing a pet peeve of mine.

GitHub has a capital H

---

.changeset/lazy-kangaroos-do.md
src/vite/plugin.ts

Fixes  n/a
This PR allows for there to be an error during buildStart without crashing the dev server

don't explode if there's an error on startup

---

integration/src/routes/plugin/query/scalars/+page.svelte
integration/src/routes/plugin/query/scalars/spec.ts
src/cmd/generators/runtime/copyRuntime.ts
src/common/config.ts
src/runtime/cache/cache.ts
src/runtime/stores/mutation.ts
src/runtime/stores/pagination/cursor.ts
src/runtime/stores/pagination/fragment.ts
src/runtime/stores/pagination/offset.ts
src/runtime/stores/pagination/query.ts
src/runtime/stores/query.ts
src/runtime/stores/store.ts
src/runtime/stores/subscription.ts

Fixes the unmarshaling issue that @fehnomenal found in #475 as well as cleans up some very noisy logging I feel bad for releasing.

Fix error when pulling custom scalars out of cache 

---

site/src/routes/index.svelte
site/src/routes/intro/fetching-data.svx
site/src/routes/intro/pagination.svx

Doc tweaks

---

site/src/routes/api/fragments.svx
site/src/routes/api/query.svx
site/src/routes/api/subscription.svx
site/src/routes/api/welcome.svx
site/src/routes/guides/authentication.svx
site/src/routes/guides/caching-data.svx
site/src/routes/guides/contributing.svx
site/src/routes/guides/faq.svx
site/src/routes/guides/pagination.svx
site/src/routes/guides/release-notes.svx
site/src/routes/guides/typescript.svx
site/src/routes/guides/working-with-graphql.svx
src/runtime/lib/network.ts

Found a few more issues with the docs that needed cleaning up. Almost there!

Doc review

---

.github/ISSUE_TEMPLATE/bug_report.yml
site/src/routes/index.svelte
site/src/routes/intro/fetching-data.svx
site/src/routes/intro/fragments.svx
site/src/routes/intro/mutations.svx
site/src/routes/intro/pagination.svx

Fixes #532 
532 caused me to look over the whole getting started section which I had apparently forgotten to do getting 0.16.0 ready 🤦 there was bound to be something. Anyway, this PR fixes everything I ran into while reading it over.

Doc fixes 8 9 2022

---

site/src/routes/guides/authentication.svx

Minor documentation fix--no ticket

Fix inconsistent naming of server hook file

---

.changeset/quiet-buses-film.md
pnpm-lock.yaml
src/common/config.ts

Fixes #592 
This PR fixes a bug introduced in #558 that prevented documents from being extracted on windows
- ~[ ] If applicable, add a test that would fail without this fix~

posixify include patterns before comparing

---

site/src/routes/api/config.svx
site/src/routes/guides/caching-data.svx
site/src/routes/guides/working-with-graphql.svx

This PR has a few  random doc  fixes as I prepare for `0.17.0`

document plugin config

---

site/src/routes/guides/release-notes.svx

After my migration, I propose a few tweak doc update to make it even clearer

doc update after my migration

---

e2e/_api/package.json
example/package.json
package.json
packages/houdini-react/package.json
packages/houdini-svelte/package.json
packages/houdini/package.json
packages/houdini/src/codegen/generators/artifacts/artifacts.test.ts
packages/houdini/src/codegen/generators/artifacts/pagination.test.ts
packages/houdini/src/codegen/generators/artifacts/policy.test.ts
packages/houdini/src/codegen/generators/definitions/schema.test.ts
packages/houdini/src/codegen/generators/persistedQueries/persistedQuery.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/codegen/transforms/paginate.ts
pnpm-lock.yaml

:package: IMPROVE: version

---

.changeset/selfish-bottles-hang.md
e2e/_api/graphql.mjs
e2e/_api/schema.graphql
e2e/sveltekit/houdini.config.js
e2e/sveltekit/src/lib/graphql/operations/MUTATION.MultipleUpload.gql
e2e/sveltekit/src/lib/graphql/operations/MUTATION.SingleUpload.gql
e2e/sveltekit/src/lib/utils/routes.ts
e2e/sveltekit/src/routes/stores/mutation-scalar-multi-upload/+page.svelte
e2e/sveltekit/src/routes/stores/mutation-scalar-multi-upload/spec.ts
e2e/sveltekit/src/routes/stores/mutation-scalar-single-upload/+page.svelte
e2e/sveltekit/src/routes/stores/mutation-scalar-single-upload/spec.ts
packages/houdini/src/runtime/lib/network.ts
packages/houdini/src/runtime/lib/networkUtils.ts
site/src/routes/guides/contributing.svx
site/src/routes/guides/faq.svx
site/src/routes/guides/uploading-files.svx

Co-authored-by: https://github.com/AlecAivazis and https://github.com/524c
Fixes #154

multipart upload support

---

e2e/next/package.json
packages/houdini-react/package.json
pnpm-lock.yaml

Prepare release

---

.changeset/pink-seahorses-drive.md
packages/houdini-svelte/src/plugin/codegen/stores/custom.ts
packages/houdini-svelte/src/plugin/codegen/stores/fragment.ts
packages/houdini-svelte/src/plugin/codegen/stores/index.ts
packages/houdini-svelte/src/plugin/codegen/stores/mutation.ts
packages/houdini-svelte/src/plugin/codegen/stores/query.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/query.ts
packages/houdini-svelte/src/plugin/codegen/stores/subscription.ts
packages/houdini-svelte/src/plugin/index.ts
packages/houdini-svelte/src/plugin/kit.ts
pnpm-lock.yaml

This PR adds a very basic way for users to provide custom store implementations. My intention is to use this to experiment with things in real projects before bringing them back to houdini.

Allow user to specify custom stores

---

.changeset/tidy-boxes-fetch.md
packages/houdini-react/package.json
packages/houdini/src/codegen/generators/runtime/index.ts
packages/houdini/src/lib/config.ts
packages/houdini/src/lib/constants.ts
packages/houdini/src/lib/fs.ts
packages/houdini/src/runtime/cache/cache.ts
vitest.setup.ts

:ambulance: FIX: change internal usage of env.TEST to env.HOUDINI_TEST

---

packages/houdini/src/runtime/lib/network.ts

move some things to the multipart context

---

README.md
packages/houdini-react/README.md
packages/houdini-svelte/README.md
packages/houdini/README.md

Fixes #657 
- Add NPM package README files with basic description. The content is the same for every package. See [README preview](https://github.com/romelperez/houdini/tree/docs/package-readme-files/packages/houdini).
- Add repository README file project badges. See [README preview](https://github.com/romelperez/houdini/tree/docs/package-readme-files).

Add NPM packages README files

---

.changeset/flat-donuts-itch.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts

Improve the detection of `VariableFunction` needed.

FIX: missing VariableFunction type

---

.changeset/perfect-lemons-approve.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts

Fixes #718
This should fix things properly now. Sorry for the inconvenience this was a stupid oversight on my part.

FIX: page/load BeforeLoadEvent types

---

e2e/sveltekit/package.json
e2e/sveltekit/src/lib/graphql/houdiniClient.ts
e2e/sveltekit/vite.config.js
pnpm-lock.yaml

_Internal_
Just to make sure we control the bundle size.
Will break the build if we reach limits.
(It's ok to increase limits on adding features & debuging, we just want have everything under control)

limits - lib reporter

---

site/src/routes/guides/typescript/+page.svx

This request adds an example on how to setup a fragment with types.
(This is my first ever contribution, so please let me know if anything should be improved)

Added typescript fragment example

---

.changeset/strange-turkeys-double.md
packages/houdini-svelte/src/plugin/kit.ts

We will only visite valid routes for Svelte

---

pnpm-lock.yaml
site/package.json
site/src/routes/guides/release-notes/+page.svx

Vercel builds are breaking. Going to try to fix it here

Fix vercel build

---

site/src/app.html
site/src/components/APIShowcase.svelte
site/src/components/DeepDive.svelte
site/src/components/GraphQLExplained.svelte
site/src/components/ThemeSwitcher.svelte
site/src/components/search/SearchDialog.svelte
site/src/components/search/SearchInput.svelte
site/src/layouts/_page.svelte
site/src/routes/+page.svelte
site/static/styles/md.css

tweak doc styling

---

e2e/sveltekit/src/lib/utils/testsHelper.ts
pnpm-lock.yaml
site/package.json
site/src/components/search/SearchDialog.svelte
site/tsconfig.json

:bug: FIX: doc search

---

site/src/lib/loadOutline.js
site/src/routes/api/cache/+page.svx
site/src/routes/api/cli/+page.svx
site/src/routes/api/config/+page.svx
site/src/routes/api/vite/+page.svx

This PR adds documentation for the programatic cache api introduced in #748

Programatic cache api docs

---

e2e/sveltekit/src/lib/utils/routes.ts
e2e/sveltekit/src/routes/stores/action-mutation/+page.server.js
e2e/sveltekit/src/routes/stores/action-mutation/+page.svelte
e2e/sveltekit/src/routes/stores/action-mutation/spec.ts
e2e/sveltekit/src/routes/stores/endpoint-query/+page.server.js
site/src/routes/api/graphql/+page.svx
site/src/routes/api/mutation/+page.svx
site/src/routes/api/query/+page.svx
site/src/routes/guides/contributing/+page.svx
site/src/routes/guides/typescript/+page.svx

- Doc update of query/endpoint
- Doc add an example of mutation/form-action
- e2e test for a mutation in form-action

DOC tweaks around endpoints

---

.changeset/poor-peaches-provide.md
packages/houdini/src/vite/ast.ts

This PR removes some logs that snuck through in #793

Remove logs

---

site/src/routes/guides/pagination/+page.svx

A couple of corrections to the documentation

fix on:click on doc

---

site/src/routes/api/mutation/+page.svx

Adds documentation as proposed in #812

Add RequestEvent in .mutate() to docs

---

.changeset/silly-spiders-grin.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/kit.ts

Fixes #817 
This PR fixes some build issues when building in docker

Docker route detection

---

.changeset/ten-plums-fetch.md
packages/houdini-svelte/src/plugin/codegen/components/index.ts

Fix typings of generated variable function for component queries

---

.changeset/kind-plants-relate.md
e2e/sveltekit/src/client.ts
packages/houdini-svelte/src/runtime/stores/pagination/cursor.ts
packages/houdini-svelte/src/runtime/stores/pagination/offset.ts
packages/houdini/src/runtime/client/documentStore.ts

Fixes #888 
This PR fixes an bug with the pagination handlers causing session information to be dropped.

Pagination session

---

.changeset/blue-adults-listen.md
packages/houdini-plugin-svelte-global-stores/src/plugin/codegen/stores/index.ts
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini/src/codegen/generators/artifacts/index.ts
packages/houdini/src/codegen/index.ts
packages/houdini/src/codegen/validators/typeCheck.ts
packages/houdini/src/lib/config.ts
packages/houdini/src/lib/types.ts
packages/houdini/src/runtime/cache/storage.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/throwOnError.ts
packages/houdini/src/runtime/client/utils/documentPlugins.ts
packages/houdini/src/runtime/lib/config.ts
packages/houdini/src/runtime/lib/types.ts
packages/houdini/src/test/index.ts
site/src/routes/api/codegen-plugins/+page.svx

This PR adds a few quality of life improvements for plugin authors such as replacing all enums with string unions

Plugin author qol

---

.changeset/bright-maps-kiss.md
packages/houdini-svelte/src/runtime/stores/subscription.ts
site/src/routes/api/subscription/+page.svx

This PR fixes a bug in the subscription logic that was preventing sessions from being passed through

Subscription session fix

---

.changeset/smooth-jokes-count.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts

Fixes #916
This should fix everything!

Fix LoadInput type gen

---

site/src/routes/guides/setting-up-your-project/+page.svx

This PR changes the setting up guide according to some feedback we got on discord

Tweak setting up your project

---

site/src/layouts/_page.svelte

Fixed navigation scrolling on small screens

Fixed navigation scrolling on small screens

---

site/src/routes/api/client/+page.svx

Fix header key in API -> Client docs

---

.changeset/nice-keys-add.md
packages/houdini/src/codegen/generators/typescript/inlineType.ts
packages/houdini/src/codegen/generators/typescript/typescript.test.ts

@include and @skip now add "undefined" to the generated TypeScript type

---

site/src/routes/intro/mutations/+page.svx
site/src/routes/intro/reusing-parts-of-a-query/+page.svx

fixing some minimal typos in the great houdini started guide

---

e2e/sveltekit/package.json
e2e/sveltekit/svelte.config.js
packages/houdini-plugin-svelte-global-stores/package.json
packages/houdini-svelte/package.json
pnpm-lock.yaml
site/package.json

This PR moves the documentation site away from vercel over to netlify

Netlify site

---

.changeset/friendly-otters-repeat.md
packages/houdini-svelte/package.json
pnpm-lock.yaml

Fixes #970 
This PR fixes the svelte dependency

fix svelte dependency

---

.changeset/four-students-itch.md
e2e/sveltekit/houdini.config.js
e2e/sveltekit/package.json
packages/houdini/src/runtime/public/cache.ts
pnpm-lock.yaml

Fixes #973 
This PR fixes a bug preventing the instability flag from validating correctly

Public cache config reference

---

site/src/routes/intro/reusing-parts-of-a-query/+page.svx

Fixes #984
First PR so if I messed something up just let me know!

Fixed props being passed to Sprite in intro project

---

.changeset/fast-spoons-join.md
e2e/_api/graphql.mjs
e2e/kit/package.json
e2e/kit/src/client.ts
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/subscriptions/[snapshot]/+page.svelte
e2e/kit/src/routes/subscriptions/spec.ts
e2e/kit/vite.config.js
packages/houdini-svelte/src/runtime/stores/subscription.ts
pnpm-lock.yaml

While putting together e2e tests for subscriptions, I ran into an issue with the `fetching` state that wasn't behaving correctly

Fix subscription fetching state

---

.changeset/lucky-ligers-build.md
packages/houdini/src/codegen/index.ts

Add an explicit error when multiple operations/fragments are found in a document

---

site/src/routes/intro/+page.svx

Fix misprint

---

.changeset/poor-clocks-decide.md
packages/houdini/src/cmd/init.ts

Fixes #1029 
This PR fixes an issue in the `init` project files for non-kit projects

clean up init template

---

site/src/routes/api/subscription/+page.svx

Documentation fixes
**Before:**
```svelte
$updates.itemUpdate.item.text
```
**After:**
```svelte
$updates.data.itemUpdate.item.text
```

Documentation update: Update subscription store to the new format

---

packages/houdini-react/src/runtime/routing/index.ts
packages/houdini-react/src/runtime/routing/lib/is_pending.tsx
packages/houdini/src/runtime/lib/types.ts

This PR updates the PendingValue type definitions in the react router

Move isPending to houdini core

---

.changeset/nine-pillows-greet.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/gc.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/staleManager.ts
packages/houdini/src/runtime/cache/storage.ts
packages/houdini/src/runtime/cache/subscription.ts
packages/houdini/src/runtime/cache/tests/reset.test.ts
packages/houdini/src/runtime/public/cache.ts
site/src/routes/api/cache/+page.svx

Fixes issue from this Discord [thread](https://discord.com/channels/1024421016405016718/1118674679440363673/1118674679440363673)

Reset Cache Functionality

---

site/src/routes/api/subscription/+page.svx

Update SSE Subscription docs

---

.changeset/old-otters-trade.md
packages/houdini-react/src/server/session.ts

If cookie name not found don't return session

react cookie

---

e2e/react/src/components/SponsorInfo.tsx
e2e/react/src/routes/+page.gql
e2e/react/src/routes/+page.tsx
packages/houdini-adapter-cloudflare/package.json
packages/houdini-react/src/runtime/hooks/useFragment.ts
turbo.json

This PR fixes a bug in `useFragment` that was getting in the way of the initial render

Fix fragment initial load in React Framework

---

.changeset/mean-apes-judge.md
packages/houdini-react/src/plugin/codegen/typeRoot.ts
packages/houdini-react/src/plugin/vite.tsx
packages/houdini/src/vite/houdini.ts

This PR is the latest in the rapid fire attempts to test CD (ensuring totally fresh installs work). Sorry for the spam everyone!

Write tsconfig before all generates

---

.changeset/red-dryers-do.md
packages/create-houdini/templates/react-typescript/package.json
packages/create-houdini/templates/react/package.json
packages/houdini/src/vite/houdini.ts
site/src/routes/api/react/+page.svx

This PR contains a few extra deployment fixes I ran into while working on a project

More deployment fixes

---

site/src/routes/api/query/+page.svx

Expanded documenation of expected props of `store.fetch`

Edited docs of store.fetch method

---

.changeset/mean-wasps-stare.md
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/pagination/query/offset-single-page/+page.svelte
e2e/kit/src/routes/pagination/query/offset-single-page/spec.ts
packages/houdini-svelte/src/runtime/stores/pagination/query.ts
packages/houdini/src/runtime/lib/pagination.ts

Fixes #1247 
This PR fixes a few bugs in the SinglePage support for offset-based pagination and includes a test to ensure they continue to function

Offset single page

---

.changeset/witty-cherries-visit.md
packages/houdini-react/src/plugin/vite.tsx
packages/houdini-react/src/runtime/clientPlugin.ts
packages/houdini-react/src/runtime/hooks/useDocumentHandle.ts
packages/houdini-react/src/runtime/index.tsx
packages/houdini-react/src/runtime/routing/Router.tsx
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/cache.ts
packages/houdini/src/runtime/client/plugins/fetchParams.ts
packages/houdini/src/runtime/router/match.ts

This PR contains a few pieces of polish that I ran into while working on a demo application

More random fixes for React bindings

---

site/src/routes/intro/reusing-parts-of-a-query/+page.svx

i change "your component library will fill with components" to "your component library will be filled with components"
Fixes #TICKET

Fixed gramma error

---

site/src/routes/intro/mutations/+page.svx

fixed grammatical error changed "only part" to "only one part "

---

.changeset/thick-chicken-impress.md
packages/houdini/src/runtime/client/documentStore.test.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/fetch.ts
packages/houdini/src/runtime/client/plugins/fetchParams.ts

This PR contains a confirmed fix for the attempt in #1330

Clean up marshaled

---

.changeset/wise-bottles-hope.md
packages/houdini-svelte/src/runtime/stores/pagination/query.ts

This PR fixes the types that still weren't correct in #1362

Properly fix return types of pagination handlers this time.

---

.github/pull_request_template.md

Fixes N/A: just a heads up for contributors

docs: update pull_request_template.md to remind running prettier

---

.changeset/orange-apricots-kiss.md
packages/houdini-svelte/src/plugin/transforms/componentQuery.test.ts
packages/houdini-svelte/src/plugin/transforms/componentQuery.ts

Merges the changes for #1469 into the `houdini-2.0` branch.

Merge PR #1469 into branch houdini-2.0

---

.changeset/mighty-games-happen.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
packages/houdini-svelte/src/runtime/types.ts

This is the same as #1487, but on the `houdini-2.0` branch.

[Houdini 2.0] Load event parameter types
