HoudiniGraphql/houdini

packages/houdini/src/generators/runtime/cache.test.ts
packages/houdini/src/generators/runtime/template/cache/cache.ts

The PR changes the index logic to accommodate types that do not support some kind of ID. This is useful to support a relay-like connection that looks something like:
```javascript
{
viewer: {
id: '1',
friends: {
edges: [
{
node: {
id: '2',
firstName: 'jane',
},
},
{
node: {
id: '3',
firstName: 'mary',
},
},
],
},
},
}
```

Embedded data

---

example/schema/schema.gql
packages/houdini/cmd/main.ts
packages/houdini/cmd/utils/writeSchema.ts

I noticed that with the current implementation of pull-schema, you have to execute the command twice because the config reads the schema before it gets updated.
I've also updated the writeSchema function to write .gql/.graphql files correctly since the current behaviour writes json into it.

Fix a bug in pull schema and write the schema to .gql or .graphql files if set in config.

---

packages/houdini-preprocess/src/transforms/mutation.ts

This PR fixes #98 and removes the check for a mutation root type. The value wasn't used anywhere and was left overs from an old implementation of the preprocessor.

Remove check for mutation rootType

---

example/package.json
lerna.json
packages/houdini-common/package.json
packages/houdini-common/src/parse.test.ts
packages/houdini-common/src/parse.ts
packages/houdini-preprocess/package.json
packages/houdini-preprocess/src/test.ts
packages/houdini-preprocess/src/transforms/index.ts
packages/houdini/cmd/generate.ts
packages/houdini/package-lock.json
packages/houdini/package.json

After struggling for a long time to get the svelte preprocessor infrastructure from #101 working, I decided to flesh out the custom parser to isolate only the top-level scripts for a document's `module` and `instance` scripts.
@thormuller @georgecrawford @pixelmund  - mind running your application with these changes and see if anything pops up? I tried to add tests for as many weird edge cases as I could but i'm sure I'm missing something.
it is available as version `0.7.2-rc.4`  which _should_  be tagged with `@next`
fixes #100

Better parser

---

README.md
packages/houdini-common/src/config.ts
packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts
packages/houdini/cmd/generators/runtime/adapter.ts
packages/houdini/runtime/query.ts

This PR separates the static-mode support from the support for bare-svelte applications by adding an addition `static` option to the config file which causes every `query` to be handled like a bare svelte app but still generates the kit adapter. I also added a svelte adapter that avoid importing from `$app` which fixes #67. Along the way I address a problem with handling errors encountered while computing variables for non-route components.

Static mode

---

packages/houdini-common/src/parse.test.ts
packages/houdini-common/src/parse.ts
packages/houdini-preprocess/src/test.ts
packages/houdini-preprocess/src/transforms/index.ts
packages/houdini/cmd/generate.ts

This PR updates houdini's internal to use the one from svelte instead of the one I recently wrote. This should keep houdini significantly more resilient and saves us the headache of maintaining complex code.

Use svelte parser instead of custom one

---

packages/houdini/cmd/generators/typescript.test.ts
packages/houdini/cmd/generators/typescript.ts
packages/houdini/cmd/utils/graphql.ts
packages/houdini/cmd/utils/index.ts

This PR fixes the input type generation to allow for recursive input types. Previously, the type generator would flatten the type definition into a single object which clearly doesn't work in an input type references itself.
closes #111

Recursive input types

---

example/package.json
packages/houdini/cmd/generate.ts
packages/houdini/cmd/generators/artifacts/artifacts.test.ts
packages/houdini/cmd/generators/artifacts/index.ts
packages/houdini/cmd/generators/artifacts/indexFile.test.ts
packages/houdini/cmd/generators/artifacts/indexFile.ts
packages/houdini/cmd/generators/runtime/indexFile.test.ts
packages/houdini/cmd/generators/typescript/index.ts
packages/houdini/cmd/generators/typescript/typescript.test.ts
packages/houdini/cmd/testUtils.ts
packages/houdini/cmd/transforms/addID.test.ts
packages/houdini/cmd/transforms/fragmentVariables.test.ts
packages/houdini/cmd/transforms/fragmentVariables.ts
packages/houdini/cmd/transforms/list.ts
packages/houdini/cmd/transforms/lists.test.ts
packages/houdini/cmd/transforms/typename.test.ts
packages/houdini/cmd/types.ts
packages/houdini/cmd/validators/noIDAlias.test.ts

This PR changes the approach when generating documents. Instead of adding additional definitions to the source document (which can confuse the generators), they are now added at the end of the pile with a `generated` flag that prevents the generators from processing them. Along the way, I also improve the document mocking utility to not require explicitly passing the document name.
fixes #133

Separate generated docs

---

.github/workflows/release.yml
.github/workflows/tests.yml
packages/houdini/package.json
yarn.lock

It seems that node version >=14.13 does not reintroduce the problems in #103, and allows for support for Vercel as discussed in #137.
Have tried version 14.12 and below, and there are issues with the graphql Kind export, and maybe others, as can be seen in the CI checks for the first commit.

Use node version >=14.13

---

packages/houdini/runtime/cache/cache.test.ts
packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/record.ts

This PR fixes the bug reported in #141 which would trigger when there was a self-reference inside of a linked list

Fix bug when unsubscribing to recursive linked lists

---

example/houdini.config.js
packages/houdini/cmd/init.ts
packages/houdini/cmd/types.ts
packages/houdini/runtime/types.ts

Hey,
just a small enhancement to enable typable configs. It's quite nice to have some confidence while changing configs and comes with basically zero cost...
Btw, thanks for your work - its great to expand the svelte-way of tackle modern frontend-problems to the graphql-client! :)

Feat: Export type ConfigFile to enable typable configs + code completion

---

packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts
packages/houdini/runtime/network.ts
yarn.lock

Closes #147
This implements the `onLoad` hook, it get's the same args as the variable functions and can return `this.error` `this.redirect` etc.
Also if you return some object from the function it get's added to the return of `load`.
e.g.
```svelte
<script context="module">
// It has access to the same arguments and this.error this.redirect as the variable functions
export function onLoad({page, session}){
if(!session.authenticated){
return this.redirect(302, '/login')
}
return {  hello: "world" }
} 
</script>
<script>
export let hello
</script>
```

Feat: onLoad Hook

---

packages/houdini/cmd/generators/typescript/inlineType.ts
packages/houdini/cmd/generators/typescript/typeReference.ts
packages/houdini/cmd/generators/typescript/typescript.test.ts
packages/houdini/cmd/transforms/list.ts
packages/houdini/cmd/utils/graphql.test.ts
packages/houdini/cmd/utils/graphql.ts
packages/houdini/runtime/cache/cache.test.ts
packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/list.ts
packages/houdini/runtime/cache/record.ts

This PR fixes the handling of lists of lists. The issue in #150 affects two different places: the `unwrapType` function used by the cli and the cache's embedding of list data.
fixes #150

List of list types

---

packages/houdini-common/src/parse.test.ts
packages/houdini-common/src/parse.ts

This PR fixes #159 by clearing the style contents before running the parser. 
This really only delays a larger problem, however. A very similar issue will happen if a user ever has a non-typescript `<script>` tag that babel can't parse. Ideally we would be able to hook into the defined list of preprocessors and run those which would normalize the javascript tags. I'm not really sure how to best pull that off so I think this is a fine patch for now.

Clear style tag content when parsing

---

packages/houdini-common/src/config.ts
packages/houdini/cmd/main.ts

Bug fixes for #162
```
benj@MacBook ~/projects/houdini/example
fix/issue-162* $ ls schema
index.cjs
benj@MacBook ~/projects/houdini/example
fix/issue-162* $ yarn generate
Error: Schema file does not exist! Create it using houdini generate -p
at new Config (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:688:23)
at file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:1067:31
at step (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:346:23)
at Object.next (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:327:53)
at fulfilled (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:317:58)
benj@MacBook ~/projects/houdini/example
fix/issue-162* $ yarn generate -p
Pulled latest schema from http://localhost:4000/graphql …
```

Address houdini generate -p errors if schema file doesn't exist

---

packages/houdini/runtime/scalars.test.ts
packages/houdini/runtime/scalars.ts

This PR fixes #166, a problem with the marshaling and unmarshaling logic which would destroy enum values.

Fix error when marshaling/unmarshaling enums

---

README.md
packages/houdini/cmd/init.ts
packages/houdini/cmd/main.ts
packages/houdini/cmd/utils/writeSchema.ts

This PR does three things:
- adds the `--pull-header` argument to `init` and `generate` allowing users to specify headers to use when pulling the schema 
- `init` now calls `generate` at the end so the user gets their initial runtime
- fix #170

Add Pull headers arg and call generate from init 

---

packages/houdini/cmd/main.ts

If generate error has nested objects, log their contents
Before
After

Nested error logging on generate command

---

packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/tests/list.test.ts

This PR updates the cache's support for operations to include payloads that are lists (ie if the user needs to add/remove/delete multiple entries at once)
fixes #169

List operations can be performed on lists of responses

---

README.md
packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts
packages/houdini/runtime/network.ts

fixes #202
Makes graphql query result data available to houdini's `onLoad` hook. 
This align's with sveltekit's design, notably allows customizing HTTP responses.
Sveltekit `onLoad` hooks now have a access to a new property on their existing single context argument:
```js
export function onLoad({ data }) {
const result = data.MyQuery
...
}
```
and for sapper, via a new argument:
```js
export function onLoad(page, session, data) {
const result = data.MyQuery
...
}
```
Following code review, the `onLoad` is now split into two hooks: `beforeLoad` and `afterLoad`
`beforeLoad` can be considered the same as the legacy `onLoad` hook. `afterLoad` is a new hook with the same call semantics as `beforeLoad`, but with an extra `data` attribute containing query data. It gets invoked after graphql …

feature: add query data to onload hooks

---

packages/houdini-preprocess/src/transforms/query.ts

I've stumbled across the #170 issue again on windows, i've gone ahead and found a simple fix, windows paths always contain back slashes, but the doc.filename forward slashes so to make the detection correct we replace all backlashes with forward slashes.

Fix isRoute detection in preprocessor

---

packages/houdini/cmd/generators/typescript/index.ts
packages/houdini/cmd/generators/typescript/typescript.test.ts

I am always forgetting that `$data` might be `undefined` since the typescript type does not specify it, so i changed the result type to be a union of the old type and `undefined`. I was not too sure if i should put it on the Query type, `$result` type or on the runtime query, mutation, etc. data types

Make result type possibly undefined

---

packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts

See #232
Maybe I went a bit overboard but I restructured the code generation a little bit to make it easier to work for me. I think it is best to review the commits in isolation as otherwise the changes to the generated code in the tests are rather confusing.
1. In commit 35f2be2c04053f344f926f2f670268ed08c41136 I removed some unneeded checks and changed the order of handling query documents, so it will match the order as defined in the svelte code.
2. In commit 867751f7df30e80081488772e6b73db38b7d5592 I took the liberty of (hopefully) improving the performance by not fetching sequentially but in parallel.
3. Commit 9ab933651d44eeab663e280c12c1e23ced60d003 is finally the meat of the PR and assigns hook results to variables, merges them if necessary and also merges `props` and `stuff`. I …

Enhance hook function returns

---

packages/houdini/cmd/generators/typescript/index.ts
packages/houdini/cmd/generators/typescript/typescript.test.ts

To simplify my typing I want to replace
```ts
export function afterLoad({
data,
params,
}: Parameters<Load>[0] & {
data: {
GetCatalogPublic: GetCatalogPublic$result;
SearchProductsPublicByCatalog: SearchProductsPublicByCatalog$result;
};
}): ReturnType<Load> {
```
with
```ts
export function afterLoad({
data,
params,
}: Parameters<Load>[0] &
GetCatalogPublic$afterLoad &
SearchProductsPublicByCatalog$afterLoad): ReturnType<Load> {
```
---
The generated types are super simple and have the form of
```ts
type <Name>$afterLoad = {
data: {
<Name>: <Name>$result
}
}
```
I tried to do a global type that is generic over `Operation<any, any>`but I failed to add the name of the type as a property to the data object. Probably I didn't understand template literal types correctly :sweat_smile:

Generate type for usage in `afterLoad`

---

lerna.json
package.json
packages/houdini/package-lock.json
packages/houdini/package.json
packages/houdini/runtime/cache/cache.ts
packages/houdini/runtime/cache/storage.ts
packages/houdini/runtime/cache/tests/subscriptions.test.ts
packages/houdini/runtime/mutation.ts
packages/houdini/runtime/scalars.test.ts
packages/houdini/runtime/scalars.ts

This PR closes #152 and adds the API for providing an optimistic response for a mutation. All of the actual work was done in #228 when I rewrote the cache's storage mechanism but I wanted to avoid releasing this portion while I collected feedback on the rewrite. Now that the cache has been used by a number of people, I feel more comfortable releasing this API.
In short, providing an optimistic response for a mutation looks something like this:
```svelte
<script>
import { mutation, graphql } from '$houdini'
export let itemID
const toggleItem = mutation(graphql`
mutation ToggleItem($id: ID!) {
toggleItem {
item {
id
checked
}
}
}
`)
</script>
<button on:click={() => {
toggleItem({ id: itemID }, {
optimisticResponse: {
toggleItem: {
item: {
id: '1',
checked: true
}
}
}
}
)}}>
toggle item …
```

Optimistic updates

---

.changeset/eleven-cherries-breathe.md
packages/houdini/runtime/cache/storage.ts
packages/houdini/runtime/cache/tests/storage.test.ts

This PR closes #258 (i hope) and fixes an issue when resolving the first layer in the cache which can happen if a mutation triggers before any queries.
cc @ClaytonFarr

handle resolving base optimistic layer

---

.changeset/rotten-frogs-deny.md
packages/houdini-preprocess/src/transforms/query.test.ts
packages/houdini-preprocess/src/transforms/query.ts

See #268 
I changed the approach to only split into storing promises and awaiting them if one `load` function has to execute more than one query.
I could not yet test it but from looking at the generated code there shouldn't be any problems.

Parallel queries

---

.changeset/violet-shoes-hide.md
package.json
yarn.lock

resolves #278 by implementing the method [husky docs suggest](https://typicode.github.io/husky/#/?id=yarn-2) to disable postinstall for publishing with [pinst](https://github.com/typicode/pinst).

add pinst to disable postinstall on packaging

---

.changeset/clean-bears-rescue.md
src/runtime/cache/cache.ts
src/runtime/cache/gc.ts
src/runtime/cache/lists.ts
src/runtime/cache/storage.ts
src/runtime/cache/subscription.ts
src/runtime/cache/tests/gc.test.ts
src/runtime/cache/tests/list.test.ts
src/runtime/cache/tests/subscriptions.test.ts
src/runtime/types.ts
yarn.lock

This PR does a few things:
- List operations are now silent. If the list hasn't been created when a mutation triggers, nothing happens. Previously, an exception was thrown which couples a mutation to the view
- If an element is appended to a list, it is added to all lists that satisfy the name and when conditions, not just the latest one to register
To Do:

Make list operations silent

---

.changeset/polite-pans-hammer.md
src/preprocess/transforms/query.test.ts
src/preprocess/transforms/query.ts

This PR closes #282 by providing a default value of `{}` to the props driven by the query response

Given component queries better default prop values

---

.changeset/sweet-ads-eat.md
package.json
yarn.lock

Potential fix for #298 
Upgrade @babel/parser to support syntax added in typescript 4.5 which is used by the latest SvelteKit / language-tools.
I published this to npm `@rmarscher/houdini@0.14.5-babel-parser.0` and confirmed it fixes the test project I created - https://github.com/rmarscher/sveltekit-houdini-typescript/commit/a2252072f8fb8aae3a66eb43067c4f3c41c9f4ae
Thanks!

Typescript 4.5 support

---

yarn.lock

When checking out this repo locally and installing the dependencies, I noticed that it causes a `yarn.lock` mutation to occur. This is probably not desired, so here's a PR to commit the change that `yarn` wants to make to the lockfile!

Remove unused entry from lockfile

---

package.json
yarn.lock

I came across this old version of TypeScript while writing #310 and finding a case where something wouldn't type-check that should have.
Removing the resolution seems safe; the tests still pass, so I figure it's worth removing to use the latest version of TypeScript instead!

Remove Resolution to TypeScript 3.9.5

---

.changeset/empty-socks-design.md
.changeset/pre.json
src/runtime/cache/cache.ts
src/runtime/cache/lists.ts
src/runtime/cache/subscription.ts
src/runtime/cache/tests/gc.test.ts
src/runtime/cache/tests/list.test.ts

This PR fixes #314 by changing the `@parentID` directive behavior to take the ID pointing to the parent of the field marked with `@paginate` or `@list` instead of the target of the fragment/query. Since this is technically a breaking change, I also put the repo in prerelease mode so we can include this fix along with #291

`@parentID` fix

---

.changeset/thin-readers-matter.md
integration/houdini.config.js
src/cmd/main.ts
src/common/config.ts
src/runtime/lib/config.ts
yarn.lock

This PR closes #318 and adds support for a glob to be passed into `schemaPath`. Additionally using `generate -p`  when the path points to multiple files (defined by `glob.hasMagic`) causes an warning since the user doesn't need to pull down their schema if its already available locally

Multiple schema files

---

.changeset/wicked-lamps-smoke.md
src/cmd/generators/typescript/index.ts
src/cmd/generators/typescript/typescript.test.ts

@alexlafroscia brought up a good point in #304 about the nullability of mutation results. This PR fixes the generated type for mutation artifacts to not be able to be `undefined`

Mutation results shouldn't be nullable by default

---

.changeset/forty-geckos-grin.md
src/runtime/inline/mutation.ts

This PR fixes an issue with the type definitions of the inline mutation's `mutate` method. I also removed some old code that was moved to the mutation store implementation.

mutation returns data directly

---

.changeset/angry-ladybugs-decide.md
src/preprocess/transforms/query.ts

query hooks are no longer deprecated since we don't want to encourage users to define their own loads (it'll break the variable call to `fetch`)

remove the query hook deprecation notice

---

.changeset/forty-experts-occur.md
src/preprocess/transforms/query.test.ts
src/preprocess/transforms/query.ts

This PR changes the load function generated by the preprocessor to only set `blocking: true` when the user defines the `afterLoad` hook

only set inline query navigation block when using afterLoad

---

.changeset/shiny-melons-rest.md
integration/src/lib/utils/routes.ts
integration/src/routes/stores/fragment-null.spec.ts
integration/src/routes/stores/fragment-null.svelte
src/runtime/lib/pagination.ts
src/runtime/lib/types.ts
src/runtime/stores/fragment.ts

When mixing a fragment into a null value, it's annoying to have to check for null before passing to an inline fragment. This PR updates the inline fragment function to accept and return null values so you can just do `data?...` in the component

Null fragment parents

---

.changeset/friendly-cameras-sort.md
src/cmd/generators/typescript/index.ts
src/cmd/generators/typescript/typescript.test.ts
src/cmd/transforms/list.ts
src/cmd/utils/flattenSelections.ts
src/common/config.ts
src/runtime/lib/config.ts

This PR sets the ground work for #349 and adds a `disableMasking` config value to configure the type generator to include fields from referenced fragments. This is especially important for users migrating to houdini from projects that did not enforce masking

Add config value to disable masking globally

---

.changeset/lazy-kings-watch.md
src/common/config.ts
src/preprocess/index.ts

This PR adds a `configFile` parameter to the preprocessor so users can specify the location of their `houdini.config.js` file in order to accommodate monorepos and other unique situations. 
closes #302

Allow users to specify path to config file for preprocessor

---

.changeset/large-islands-exercise.md
integration/houdini.config.js
integration/src/lib/utils/routes.ts
integration/src/routes/preprocess/query/+QueryComponent.svelte
integration/src/routes/preprocess/query/_QueryComponent.svelte
integration/src/routes/preprocess/query/isRoute.spec.ts
integration/src/routes/preprocess/query/isRoute.svelte
src/common/config.ts
src/preprocess/transforms/query.ts
src/runtime/lib/config.ts

This PR improves the logic for distinguishing a route from a component. Queries can now be inside of `_NonRouteComponent.svelte` and it will be treated as a component query instead of a route. 
fixes #281

Improve isRoute logic

---

.changeset/cool-games-refuse.md
integration/src/routes/stores/pagination/query/forward-cursor.spec.ts
src/runtime/stores/query.ts

This PR fixes a bug that caused the pageInfo field to be an array instead of an object

Fix incorrect pageInfo type

---

.changeset/rich-seahorses-change.md
src/preprocess/index.ts
src/preprocess/transforms/fragment.test.ts
src/preprocess/transforms/fragment.ts
src/preprocess/transforms/query.test.ts
src/preprocess/transforms/query.ts
src/runtime/stores/query.ts

This PR improves the preprocessor's reliability by updating the imports to point directly to the path avoiding any circular import issues

Preprocess direct imports

---

.changeset/green-chairs-reflect.md
.changeset/yellow-suns-scream.md
integration/.npmrc
src/cmd/generate.ts
src/cmd/generators/artifacts/index.ts
src/cmd/generators/artifacts/indexFile.test.ts
src/cmd/generators/artifacts/indexFile.ts
src/cmd/generators/definitions/enums.ts
src/cmd/generators/runtime/adapter.ts
src/cmd/generators/runtime/copyRuntime.ts
src/cmd/generators/stores/index.ts
src/cmd/generators/typescript/index.ts
src/cmd/utils/cleanupFiles.ts

Add Predictability of file content by sorting imports. 
Like this, we don't need to generate the same index file over and over. (as `writeFile` will not write the file if it's the same content)
Also not copying `/runtime/adapter.js` as it will be replaced by the framework choice. (today the file was written twice at each generate)
I believe that we will have less issues while in dev mode generating in the background. (To follow after this PR merged)
Adding also `deleted` items

Feat - Generate perf improvements

---

.changeset/great-rocks-wait.md
src/preprocess/transforms/query.test.ts
src/preprocess/transforms/query.ts
src/runtime/lib/context.ts
src/runtime/lib/types.ts
src/runtime/stores/query.ts

This PR fixes a bug with the values passed to the variable function for component queries
closes #421

Fix `stuff` bug in component query variables

---

.changeset/slow-rats-repeat.md
src/cmd/transforms/paginate.ts
src/cmd/validators/typeCheck.ts

Linked to https://github.com/HoudiniGraphql/houdini/issues/433
---

Node interface - warning if not properly defined && error on usage

---

src/cmd/generators/stores/fragment.ts
src/cmd/generators/stores/mutation.ts
src/cmd/generators/stores/query.test.ts
src/cmd/generators/stores/query.ts
src/cmd/generators/stores/subscription.ts
src/cmd/generators/typescript/index.ts
src/cmd/generators/typescript/typescript.test.ts

See https://github.com/HoudiniGraphql/houdini/discussions/475#discussioncomment-3467838
I also unified and fixed some things I stumbled over.
Does this need a changeset?

Generate input types (and more fixes)

---

.changeset/stale-foxes-joke.md
src/cmd/validators/typeCheck.test.ts
src/cmd/validators/typeCheck.ts

IMPROVE: Message when @list directive and graphql client type error

---

.changeset/metal-panthers-smoke.md
src/cmd/generators/runtime/adapter.ts
src/runtime/adapter.ts
src/runtime/lib/index.ts
src/runtime/stores/query.ts
src/vite/fsPatch.ts

This issues brought up by @ymc9 here: https://github.com/HoudiniGraphql/houdini/discussions/475#discussioncomment-3473852. They mostly revolve around issues when `framework: "svelte"`

Ymc9 redirect fixes

---

.changeset/tricky-mangos-brake.md
.changeset/twenty-crabs-admire.md
.github/pull_request_template.md
integration/src/lib/utils/routes.ts
integration/src/routes/plugin/query/onError/+page.svelte
integration/src/routes/plugin/query/onError/+page.ts
integration/src/routes/plugin/query/onError/spec.ts
site/src/routes/api/config.svx
site/src/routes/api/routes.svx
site/src/routes/guides/faq.svx
site/src/routes/guides/migrating-to-016.svx
site/src/routes/guides/setting-up-your-project.svx
src/cmd/generators/kit/index.ts
src/cmd/generators/kit/kit.test.ts
src/cmd/generators/runtime/copyRuntime.test.ts
src/cmd/validators/uniqueNames.ts
src/common/config.ts
src/runtime/lib/config.ts
src/runtime/lib/network.ts
src/runtime/stores/query.ts
src/vite/plugin.ts
src/vite/schema.ts
src/vite/transforms/kit.test.ts
src/vite/transforms/kit.ts

- Adds `onError` handler to customize the logic for a specific route (it replaces the `throw` so it can be used to suppress an error if the user wants
- add `quietQueryError` config option to prevent all query errors from being thrown @ymc9
- documentation tweaks

Error behavior

---

.changeset/nine-cherries-bow.md
src/cmd/generators/runtime/adapter.ts
src/runtime/lib/network.ts
src/runtime/stores/mutation.ts
src/runtime/stores/pagination/cursor.ts
src/runtime/stores/pagination/offset.ts
src/runtime/stores/query.ts
src/vite/transforms/kit/init.test.ts
src/vite/transforms/kit/init.ts
src/vite/transforms/kit/load.test.ts
src/vite/transforms/kit/session.test.ts
src/vite/transforms/kit/session.ts

Holy cow, so many exciting updates :joy: Thanks @AlecAivazis for pushing the auth/session stuff to the finish :tada: 
Houdini nagged me to always set a session (otherwise it claims there is an error during `passServerSession`) even though the user is not authenticated. Instead of just `houdini.setSession(undefined)` I decided to clean this up and move the check to the usage of `session` in the fetch function. I found no easy way to test this without creating another testing app that does not set the session but I verified the behavior locally.
I also fixed a bug where the session data was not correctly extracted from `$page.data`. And debatable: I inlined the `passServerSession` method to prevent user confusion.

Do not force all users to set a session

---

.changeset/tame-cups-end.md
src/cmd/init.ts

Of course, 2 seconds after I merge `0.16.0` it occurred to me to check something and I found an issue. This PR updates the init command to conform to the latest files created by `npm create svelte@latest init`.  The only needed change is that the vite config file can be `.ts` in a typescript project.

vite config is now a typescript file

---

.changeset/red-jokes-invent.md
src/cmd/init.ts

Fixes _not a ticket_
In typescript before this PR, the generated file have this name: `.ts`. this PR fixes this.

:bug: FIX: file name & content

---

.changeset/olive-carrots-fry.md
src/common/config.ts
src/common/fs.ts

Fixes #536
Looking up for `./node_modules/houdini`

:sparkles: NEW: mono repo support

---

.changeset/neat-jokes-lick.md
src/vite/transforms/kit/load.test.ts
src/vite/transforms/kit/session.test.ts
src/vite/transforms/kit/session.ts

Fixes #544 
This PR fixes an issue introduced in #542 that hid the data returned from `+layout.server.js` 
-  this is tricky because we also want a test that we are able to fake the file if it doesn't exist. I'm opting to leave things how they are now since the changes are pretty clear

pass all of server.js data from root layout

---

.changeset/tidy-foxes-melt.md
integration/src/routes/stores/mutation-update/+page.svelte
integration/src/routes/stores/mutation-update/+page.ts
src/runtime/stores/query.ts

Fixes #543 
This was a good find @fehnomenal! Turns out if unsubscribe ran after `fetch` we were left with no subscription to the cache

Fix error when unsubscribing from cache between fetch and render

---

.changeset/honest-avocados-stare.md
integration/src/lib/utils/routes.ts
integration/src/routes/pagination/query/offset-variable/+page.svelte
integration/src/routes/pagination/query/offset-variable/+page.ts
integration/src/routes/pagination/query/offset-variable/spec.ts
src/runtime/stores/pagination/offset.ts

Fixes #446
This PR fixes a bug when the limit argument of an offset-based paginated query was driven by a query variable.

Offset pagination with variables

---

.changeset/fast-timers-allow.md
src/cmd/pullSchema.ts

Fixes #549 
This PR fixes an issue that was preventing the configured pull headers from being included when using the `pull-schema` command

mix config headers when pulling schema

---

.changeset/itchy-sheep-build.md
src/common/__mocks__/config.invalid.mock
src/common/config.test.ts
src/common/config.ts

Fixes #562
Will throw a usable error when the config file is malformed like:
```
Error: Could not load config file at file:///path-to/houdini.config.js.
Unexpected identifier
at readConfigFile (file:///Users/danielhritcu/GitHub/houdini/build/vite-esm/index.js:156721:15)
...
```
Instead of the generic
```
SyntaxError: Unexpected identifier
at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
at ESMLoader.moduleProvider (node:internal/modules/esm/loader:469:14)
at async link (node:internal/modules/esm/module_job:67:21)
```

throw if can not import config file

---

.changeset/mean-mice-help.md
.changeset/short-jeans-roll.md
pnpm-lock.yaml
src/vite/index.ts
src/vite/schema.ts

Addresses possible fix mentioned in #549
Due to not being able to setup the development environment (see #564). I was unable to run pnpm run tests. 
This fix changes the signature of the schema function the vite plugin. This change allows users to define additional user config via the vite plugin. This is beneficial for the end-user as it adds an additional layer of security, through the use of environment variables that are loaded through `.env` files. Currently, must use system-wide environment variables in order to keep data private.
```js
// vite.config.ts
import { sveltekit } from '@sveltejs/kit/vite';
import houdini from 'houdini/vite';
import { defineConfig, loadEnv } from 'vite';
const config = defineConfig(({ mode }) => {
// loads env files e.g.
const env = loadEnv(mode, …
```

Change signature of schema to enable extraConfig when pulling

---

.changeset/healthy-ladybugs-speak.md
.changeset/tame-peaches-stare.md
integration/src/routes/stores/ssr-[userId]/+page.ts
rollup.config.js
src/common/extractLoadFunction.ts
src/runtime/stores/query.ts

Fixes #570
This PR fixes an issue I was debugging with @endigma that was causing subscriptions to be cleared when `lastVariables` was null. The first version of this PR just removes that check since its no longer a leak for a store to remember its last variables (stores aren't global). If everything passes, I'm going to poke around the integration tests to make sure nothing is funky.

Fix issue removing store subscriptions

---

integration/src/routes/stores/nested-lists/+layout.svelte
integration/src/routes/stores/nested-lists/inner/+page.svelte

Hey @Alec
I'm not sure what the data format is for these queries but is there some nested information available on the User that we can use to test this? In this example **only** the nested->something value is mutated on the parent store when the child query changes, and the other values (e.g. id, name) are fine

Nested list cache bug

---

site/src/routes/guides/faq.svx

Docs edit referenced in #589
Added information about using .env files during the vite preprocessing step.
Not sure if I need to add a changeset so I haven't yet. Please inform me if I do, as it doesn't directly affect the user API.
I also just placed this at the bottom. Please feel free to edit  the order to your liking.

added extra config info to docs

---

.changeset/brown-onions-smile.md
src/cmd/generate.ts

Fixes #586 
This PR makes the document collection step ignore any paths matching `Config.schemaPath`

don't include the schema path as a source document

---

.changeset/smart-singers-battle.md
packages/houdini-svelte/src/plugin/transforms/kit/load.test.ts
packages/houdini-svelte/src/plugin/transforms/kit/load.ts

Fixes #602 
This PR tweaks the load generator so that it only adds enforces a `data` prop when there are inline queries that would use it

only add data prop with inline queries

---

.changeset/great-pens-return.md
e2e/sveltekit/playwright.config.ts
packages/houdini-svelte/src/plugin/fsPatch.ts

Fixes #640 
Turns out that with some versions of node, the directory gets a trailing stash which confused the fsPatch. This PR fixes it by trimming the trailing stash

address trailing statsh in is_root_route

---

.changeset/funny-kings-explode.md
packages/houdini-svelte/src/plugin/codegen/stores/fragment.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/fragment.ts
packages/houdini-svelte/src/plugin/codegen/stores/mutation.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/query.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/subscription.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/subscription.ts

Fixes #688 
This PR fixes an issue in the generated subscription stores that was accidentally creating a double import 🤦 While I was there, I also added a few missing tests

Subscription double import

---

.changeset/clean-boxes-tell.md
e2e/_api/schema.graphql
e2e/sveltekit/src/lib/utils/routes.ts
e2e/sveltekit/src/routes/plugin/subscription/renders/+page.svelte
e2e/sveltekit/src/routes/plugin/subscription/renders/spec.ts
packages/houdini-svelte/src/plugin/codegen/stores/fragment.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/mutation.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/subscription.test.ts
packages/houdini-svelte/src/plugin/codegen/stores/subscription.ts

Fixes n/a
This PR adds the artifact import to the generated subscription stores

add subscription artifact :facepalm:

---

.changeset/fifty-feet-prove.md
e2e/_api/server.mjs

Refs #695
Fixes #695
- [N/A] If applicable, add a test that would fail without this fix

Add an explicit hostname to e2e/_api/server.mjs to make the end-to-end tests work on macOS

---

packages/houdini-react/package.json
packages/houdini-svelte/package.json
packages/houdini/package.json

Fixes #698
- Add NPM packages `files` setting with only `./build` package folder.
- Add NPM packages metadata.

Fix NPM packages exports and metadata

---

.changeset/many-trainers-warn.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts

fixes #713, fixed #712
Hi there, was reviewing the code and I realised that beforeLoad and onError didn't have the correct type imports if they came from a layout. I modified the function to accept an input + some minor structural changes. 
I also increased test coverage to prevent this in the future.
All tests pass locally.

FIX: onError and beforeLoad have hardcoded imports

---

.changeset/mean-bananas-smell.md
e2e/sveltekit/package.json
example/package.json
package.json
packages/houdini-svelte/package.json
packages/houdini-svelte/src/plugin/index.ts
packages/houdini/package.json
pnpm-lock.yaml
site/package.json
site/svelte.config.js

Following [sveltekit@1.0.0-next.560](https://github.com/sveltejs/kit/blob/53e034b2ee49866c6f19ec8707c3837fbe08cd7a/packages/kit/CHANGELOG.md#100-next560) [breaking] Rename `prerendering` to `building`
Before **1.0.0-next.560** keep [houdini-svelte@0.17.13](https://www.npmjs.com/package/houdini-svelte/v/0.17.13)
From **1.0.0-next.560** take the new version

Update for kit 560 changes

---

.changeset/new-plums-sing.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts

Fixes an issue with `AfterLoadReturn`, `BeforeLoadReturn` and `OnErrorReturn` types.

Fix generated types referencing onError, afterLoad and beforeLoad

---

.changeset/old-trees-tap.md
packages/houdini/src/codegen/generators/artifacts/artifacts.test.ts
packages/houdini/src/codegen/generators/definitions/schema.test.ts
packages/houdini/src/codegen/transforms/list.ts
packages/houdini/src/codegen/transforms/lists.test.ts
packages/houdini/src/codegen/utils/objectIdentificationSelection.test.ts
packages/houdini/src/codegen/utils/objectIdentificationSelection.ts
packages/houdini/src/codegen/validators/typeCheck.ts
packages/houdini/src/runtime/lib/config.ts
packages/houdini/src/test/index.ts
site/src/routes/guides/caching-data/+page.svx
site/src/routes/guides/setting-up-your-project/+page.svx

Taking into account `custom IDs` for global identification in `@list`
Also, adding paginate error only on paginate directive

@list & custom IDs

---

.changeset/green-tables-share.md
.changeset/pretty-experts-fly.md
packages/houdini-svelte/package.json
packages/houdini-svelte/src/plugin/index.ts
packages/houdini/src/cmd/generate.ts
packages/houdini/src/cmd/pullSchema.ts
packages/houdini/src/lib/config.ts
packages/houdini/src/runtime/lib/config.ts
packages/houdini/src/vite/schema.ts
pnpm-lock.yaml
site/src/routes/api/config/+page.svx

Fixes #759 #780 
This PR adds a new hook to the plugin setup `env` that lets plugins define custom environment variables. The svelte plugin uses this hook to load environment variables using vite's `loadEnv` util and follows any configuration values set by the user's `svelte.config.js` file

Svelte plugin loads env vars from vite with kit config

---

.changeset/smart-zebras-turn.md
packages/houdini/src/codegen/generators/typescript/imperativeCache.test.ts
packages/houdini/src/codegen/generators/typescript/imperativeCache.ts

This PR fixes an issue with the generated typedefs for lists

Cache list operation types

---

.changeset/dull-starfishes-matter.md
packages/houdini-svelte/src/plugin/fsPatch.ts
packages/houdini-svelte/src/plugin/index.ts
packages/houdini/src/runtime/lib/config.ts
site/src/routes/api/config/+page.svx

Fixes #739 
This PR extends the existing `static` config value for the svelte plugin to prevent the session infrastructure from being generated since a `.server.js` file confuses kit when prerendering applications

Fix error when prerendering application

---

.changeset/brown-jobs-admire.md
packages/houdini-svelte/src/plugin/transforms/kit/load.test.ts
packages/houdini-svelte/src/plugin/transforms/kit/session.test.ts
packages/houdini/src/vite/ast.ts

Fixes #792 
This PR fixes a bug when using the `satisfies` keyword with load functions

Load with satisfies expression

---

.changeset/heavy-pumas-wink.md
packages/houdini-svelte/src/plugin/codegen/stores/mutation.ts

This PR fixes the mutation store to never have `undefined` as a return type (again)

mutation result can never be undefined

---

.changeset/forty-pugs-exercise.md
e2e/_api/graphql.mjs
e2e/sveltekit/src/routes/plugin/query/onError/+page.svelte
e2e/sveltekit/src/routes/plugin/query/onError/+page.ts
e2e/sveltekit/src/routes/plugin/query/onError/spec.ts
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts

This PR fixes the generated types for the onError hook to use the `HttpError` type provided by Kit

fix error type in onError handler

---

.changeset/tasty-bags-end.md
.graphqlrc.yaml
packages/houdini/src/cmd/init.ts

Update the default `.graphqlrc.yaml` to check for svelte files.

:sparkles: NEW: init with svelte files containing graphql things

---

site/src/routes/guides/pagination/+page.svx
site/src/routes/guides/uploading-files/+page.svx

Before
```svelte
{#if $userInfo.pageInfo.hasNextPage}
<button on:click=={userInfo.loadNextPage}>
load more
</button>
{/if}
```
After:
```svelte
{#if $userInfo.pageInfo.hasNextPage}
<button on:click={userInfo.loadNextPage}>
load more
</button>
{/if}
```
Fixes typo
- [] If applicable, add a test that would fail without this fix
- [] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [] Includes a changeset if your fix affects the user with `pnpm changeset`

Fix typo in the documentation

---

.changeset/green-walls-battle.md
packages/houdini/src/codegen/generators/artifacts/selection.test.ts
packages/houdini/src/codegen/utils/flattenSelections.ts

Fixes #819 
This PR fixes a bug during artifact generation when computing the selection of a query that contained a reference whose immediate children were inline fragments (ie for a union or interface).

fix dangling inline fragments when flattening fragments with unions

---

packages/houdini-svelte/src/plugin/kit.ts

Fixes an issue due to the wrong order in merging custom stores configuration: in case only a subset of the standard store is customized, the names of the remaining ones get lost.

Change spread order to get deep merge

---

.changeset/plenty-llamas-deliver.md
packages/houdini/src/lib/config.ts
packages/houdini/src/vite/index.ts

Fixes https://discord.com/channels/1024421016405016718/1068209851047616663/1068209851047616663
Reload the config on schema change.

On schema change, revalidate documents

---

.changeset/dull-pianos-greet.md
e2e/sveltekit/src/lib/utils/routes.ts
e2e/sveltekit/src/routes/plugin/load/pageQuery-with-server/+page.gql
e2e/sveltekit/src/routes/plugin/load/pageQuery-with-server/+page.svelte
e2e/sveltekit/src/routes/plugin/load/pageQuery-with-server/spec.ts
packages/houdini-svelte/src/plugin/fsPatch.ts

This PR fixes an issue raised in discord that was preventing a `+page.gql` from loading if there was a `server` file.

Fix page.server files

---

.changeset/weak-islands-stare.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/storage.ts
packages/houdini/src/runtime/cache/stuff.ts
packages/houdini/src/runtime/cache/subscription.ts
packages/houdini/src/runtime/client/client.test.ts
packages/houdini/src/runtime/client/documentStore.test.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/index.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/injectedPlugins.ts
packages/houdini/src/runtime/client/utils/documentPlugins.ts
packages/houdini/src/runtime/lib/flatten.test.ts
packages/houdini/src/runtime/lib/flatten.ts
packages/houdini/src/runtime/lib/types.ts
site/src/routes/api/client-plugins/+page.svx
site/src/routes/api/client-plugins/Authoring.svx

This PR makes it so that client plugins can return `(ClientHook | null | (ClientHook | null ClientPlugin)[]` allowing users to easily toggle functionality depending on configuration values:
```javascript
import { plugin } from 'houdini'
import externalPlugin from 'third-party'
import externalPlugin2 from 'third-party2'
const sayHello: ClientPlugin = ({ include }) => {
return [
{
start(ctx, { next }) {
next(ctx)
},
},
externalPlugin,
include ? externalPlugin2 :  null
]
}
```

Client plugins list of lists

---

.changeset/fresh-penguins-deliver.md
.changeset/honest-cheetahs-cheer.md
packages/houdini/src/codegen/generators/definitions/enums.test.ts
packages/houdini/src/codegen/generators/definitions/enums.ts
packages/houdini/src/codegen/generators/typescript/addReferencedInputTypes.ts
packages/houdini/src/codegen/generators/typescript/documentTypes.ts
packages/houdini/src/codegen/generators/typescript/imperativeTypeDef.test.ts
packages/houdini/src/codegen/generators/typescript/imperativeTypeDef.ts
packages/houdini/src/codegen/generators/typescript/inlineType.ts
packages/houdini/src/codegen/generators/typescript/typeReference.ts
packages/houdini/src/codegen/generators/typescript/types.ts
packages/houdini/src/codegen/generators/typescript/typescript.test.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/index.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/cache.ts
packages/houdini/src/runtime/client/plugins/fetch.ts
packages/houdini/src/runtime/client/plugins/fetchParams.ts
packages/houdini/src/runtime/client/plugins/mutation.ts
packages/houdini/src/runtime/client/plugins/query.ts
packages/houdini/src/runtime/client/plugins/subscription.ts
packages/houdini/src/runtime/client/plugins/throwOnError.ts
packages/houdini/src/runtime/lib/types.ts
site/src/routes/api/client/+page.svx
site/src/routes/api/subscription/+page.svx
site/src/routes/guides/release-notes/+page.svx

This PR changes the way enums are handled to be a generated constant object instead of a typescript enum. The generated types reference values of this object which means users can pass strings if they want or they can import `MyEnum` like usual and use the object

Enum as const pojo

---

site/src/routes/api/client-plugins/+page.svx

I noticed these while following the 1.0 migration docs and migrating our custom client fetch to a network plugin. Thanks!

A couple typos in new client plugins doc

---

.changeset/cool-panthers-juggle.md
e2e/sveltekit/src/routes/stores/action-mutation/+page.svelte
packages/houdini-svelte/src/runtime/stores/mutation.ts
site/src/routes/guides/release-notes/+page.svx

This PR changes the return type of `MutationStore.mutate` to include the full result instead of just the value of `data`
cc @xmlking

Mutation response

---

.changeset/sharp-kangaroos-admire.md
packages/houdini-svelte/package.json
packages/houdini-svelte/src/plugin/fsPatch.ts
packages/houdini-svelte/src/plugin/transforms/index.ts
packages/houdini/src/codegen/generators/artifacts/artifacts.test.ts
packages/houdini/src/codegen/generators/artifacts/index.ts
packages/houdini/src/codegen/generators/artifacts/pagination.test.ts
packages/houdini/src/codegen/generators/artifacts/plugins.test.ts
packages/houdini/src/codegen/generators/artifacts/policy.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/lib/graphql.ts
packages/houdini/src/lib/types.ts
packages/houdini/src/vite/houdini.ts
pnpm-lock.yaml

This PR should fix the source map issues that been cropping up

Sourcemaps

---

.changeset/pretty-lobsters-push.md
packages/houdini/src/runtime/lib/scalars.test.ts
packages/houdini/src/runtime/lib/scalars.ts

This PR changes the behavior of marshaling route params so that `NaN` gets passed as undefined

Nullable optional route param marshal

---

.changeset/fresh-cameras-press.md
e2e/sveltekit/src/routes/stores/mutation/spec.ts
packages/houdini/src/runtime/client/documentStore.test.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/cache.ts
packages/houdini/src/runtime/client/plugins/fetch.ts
packages/houdini/src/runtime/client/plugins/query.ts
packages/houdini/src/runtime/client/plugins/subscription.ts
packages/houdini/src/runtime/lib/types.ts

This PR applies some feedback from @seppahbaws in order to make the `variables` key on `DocumentStores` more ergnomic. Now, the type is `_Input | {}` and the runtime uses `{}` as the default/empty value

Query variable type

---

.changeset/rude-clocks-thank.md
e2e/sveltekit/src/routes/stores/mutation/spec.ts
packages/houdini/src/runtime/client/documentStore.test.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/cache.ts
packages/houdini/src/runtime/lib/types.ts

This PR reverts #908 and allows the `variables` key of the query store to be `null` (indicating no variables have been set)

Revert null query variables

---

site/src/routes/intro/fragments/+page.svx
site/src/routes/intro/mutations/+page.svx
site/src/routes/intro/pagination/+page.svx

No ticket for this PR.
I went through the intro docs and found a couple things details that needed fixing:
* Fix typo: SprintInfo -> SpriteInfo
* Fix typo: FavoriteContainer -> FavoritesContainer
* Fix some file names in code snippets
* Add default parameter to graphql "Info" query
* Update Info query in some snippets to use fragments instead of explicit fields
* Fix snippet code: Info.loadPrevMove -> loadPrevMove
* Other small typos

Several small fixes in intro docs

---

.changeset/gold-spies-fry.md
.changeset/seven-turkeys-sleep.md
packages/houdini/src/codegen/generators/typescript/typescript.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.ts
packages/houdini/src/codegen/validators/typeCheck.test.ts
packages/houdini/src/codegen/validators/typeCheck.ts
packages/houdini/src/test/index.ts
pnpm-lock.yaml

fixes #920, fixes #120 
This PR fixes an issue in the logic that parses the `type` string when defining fragment arguments. Along the way, I also improved the argument validation logic so that you can't pass `[1]` when a fragment argument is defined as `String`.

Fragment argument validation

---

.changeset/bright-suns-listen.md
e2e/sveltekit/src/routes/pagination/fragment/backwards-cursor/+page.svelte
e2e/sveltekit/src/routes/pagination/fragment/bidirectional-cursor/+page.svelte
e2e/sveltekit/src/routes/pagination/fragment/forward-cursor/+page.svelte
e2e/sveltekit/src/routes/pagination/fragment/offset/+page.svelte
e2e/sveltekit/src/routes/plugin/fragment/update/+page.svelte
packages/houdini-plugin-svelte-global-stores/src/test/index.ts
packages/houdini-svelte/src/plugin/codegen/fragmentTypedefs/fragmentTypedefs.test.ts
packages/houdini-svelte/src/plugin/codegen/fragmentTypedefs/index.ts
packages/houdini-svelte/src/runtime/stores/fragment.ts
packages/houdini-svelte/src/runtime/stores/pagination/cursor.ts
packages/houdini-svelte/src/runtime/stores/pagination/fragment.ts
packages/houdini-svelte/src/runtime/stores/pagination/offset.ts
packages/houdini-svelte/src/runtime/stores/pagination/query.ts
packages/houdini-svelte/src/runtime/types.ts
packages/houdini-svelte/src/test/index.ts
packages/houdini/src/test/index.ts

This PR fixes the type definitions for the `fragment` function so that if the parent is not allowed to be null, `data` will also be non-null.

Fragment null parent typedefs

---

.changeset/itchy-geckos-prove.md
packages/houdini-svelte/src/runtime/stores/base.ts
packages/houdini-svelte/src/runtime/stores/mutation.ts
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini-svelte/src/runtime/stores/subscription.ts
packages/houdini/src/runtime/client/plugins/subscription.ts

Fixes #932 
This PR fixes a bug in the subscription plugin that would cause the subscription factory to be called multiple times if there were simultaneous subscriptions.

Subscriptions reuse existing client

---

.changeset/old-walls-cover.md
packages/houdini/src/runtime/client/plugins/subscription.ts

This PR fixes an issue reporting in discord that caused subscriptions to not recreate their session if `listen` was called after `unlisten` when the `checkValue` didn't actually change.

Subscription listen then unlisten

---

site/src/components/search/SearchInput.svelte

This PR hides the keyboard combo indicator on the search box on mobile phones, so that the search box looks a bit nicer. Phones (usually) don't have a keyboard attached, so it was useless information anyways.
I know it's a small edit, but it was something I noticed and was annoying me a tiny bit 🙂 
| before | after |
|---|---|
| ![image](https://user-images.githubusercontent.com/10342829/219071819-9f74218a-29b2-4ec1-9545-d662ef446cf0.png) | ![image](https://user-images.githubusercontent.com/10342829/219071890-a89d5692-2274-4c97-b5ff-504b1623daab.png) |

Hide documentation search box key combo on mobile phones

---

.changeset/warm-crews-drive.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts

This PR is the result of a thread @AlecAivazis and I had on discord, where all the generated code was simply *missing* / not there in the first case, which was very difficult to debug on my own.
Now, we throw a warning during the `houdini-svelte` codegen step.

Svelte: Warn if "include" config key doesn't specify js files

---

.changeset/cyan-pandas-tan.md
.changeset/quick-yaks-walk.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/cache.ts

This PR contains some fixes to some issues that I encountered while putting https://github.com/grafbase/grafbase/pull/214 together. The most important one is a fix for `CacheAndNetwork` policies. 
Also, Grafbase has a "bug" in their implementation of live queries that sends more fields than the query specifically asks for. This was breaking houdini which requires that responses match the selection object. While they fix this issue, I added a small work around that makes the cache fail silently and skip over fields that it doesn't recognize.

CacheAndNetwork policy and other Grafbase fixes

---

.changeset/fast-islands-nail.md
packages/houdini/src/codegen/generators/artifacts/artifacts.test.ts
packages/houdini/src/codegen/transforms/addID.test.ts
packages/houdini/src/codegen/transforms/addID.ts
packages/houdini/src/codegen/transforms/typename.test.ts

This PR fixes a bug with the codegen's logic for adding key fields to a selection. The logic was previously only considering fields but unions that don't have fields themselves are made up of inline fragments which also need their keys added. Luckily, multiple fields showing up isn't a problem so we can be kind of lazy about this and just always add it.

Add ids to the generated selection of inline fragments

---

.changeset/blue-toes-carry.md
e2e/sveltekit/src/client.ts
packages/houdini/src/runtime/client/plugins/throwOnError.ts
site/src/routes/api/client/+page.svx

As discussed in Discord ([link to conversation](https://discord.com/channels/1024421016405016718/1077532514928820225)), passing the `ctx` to throwOnError in the client would be useful when trying to figure out which query exactly it is that is giving the error.
~~I've gone ahead and implemented a demo of this in the e2e project, but it should still work if you don't need to use the ctx.~~ It was messing up the e2e tests, so I have reverted this.

Pass ctx to the throwOnError error handler

---

.changeset/stupid-tomatoes-sing.md
.github/workflows/tests.yml
README.md
e2e/kit/src/app.html
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/+page.svelte
e2e/kit/src/routes/customIDs/spec.ts
e2e/kit/src/routes/stores/mutation-opti-list/+page.svelte
e2e/kit/src/routes/stores/mutation-opti-list/spec.ts
e2e/kit/vite.config.js
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/tests/availability.test.ts
packages/houdini/src/runtime/cache/tests/list.test.ts
packages/houdini/src/runtime/public/list.ts
pnpm-lock.yaml

Optimistic Mutation in a list

---

.changeset/brown-icons-call.md
packages/houdini-svelte/src/runtime/stores/pagination/query.ts

This PR fixes a timing issue with paginated stores. Now, we make sure that `initClient` is called before we build the pagination handlers

Fix initialization issue in paginated queries

---

.changeset/tender-ducks-cough.md
packages/houdini/src/lib/config.ts

Since JS [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) treats `null` as `nullish` value, passing over `null` in `watchSchema.interval` forcefully makes the value to `2000`, not `null`.
Houdini handles `2000`, `0`, and `null` differently in its `watchSchema.interval` config, but this bug prevents users from using `null` as its value to dictate the behavior to never pull the schema on any circumstances.
This patch fixes that behavior.

Handle `null` in `watchSchema.interval` properly

---

.changeset/strange-adults-rush.md
packages/houdini/src/runtime/client/documentStore.test.ts
packages/houdini/src/runtime/client/documentStore.ts

This PR fixes a bug I was having, where list operations on a list inside of a fragment with arguments caused the fragment's store data to be set to null.
Apparently the fragment's arguments never got marshaled, so in the fragment store the variables was an empty object, and thus the lists in the fragment never got added to the cache's `lists` collection.
@AlecAivazis I was not entirely sure how to write a proper test case for this, some help with writing one would be appreciated :)

Allow fragment arguments to get marshaled properly

---

.changeset/gorgeous-turtles-joke.md
packages/houdini/src/lib/config.ts

Fixes #1035.
Making test cases with PnP environment mocking is not viable, really.
But I can confirm that _it works on my machine_ ¯\\_(ツ)_/¯

Add support for Yarn's PnP mode

---

site/src/routes/api/config/+page.svx

Clarifies that scalar marshal/unmarshal functions are called on null values.

Update scalars documentation for null values

---

.changeset/twenty-months-cover.md
packages/houdini/src/runtime/client/plugins/fetch.ts
packages/houdini/src/runtime/client/plugins/subscription.ts

Rationale: #832
This PR changes the default behavior of `fetch` built-in plugin to include `operationName` in the fetch payload along with the `query` and `variables`.
This PR also changes the signature of `subscription` built-in plugin to pass `operationName` to user-provided subscription function so the user can easily interacts with it in their implementation.
Several popular implementations such as `graphql-ws` and `graphql-sse` do already utilize `operationName` argument if it is passed into their `subscribe` function. So in the most cases if we pass `operationName` to `subscribe` function it would be automatically included in the corresponding payload, which is also good for interoperability.
This also makes Houdini aligned with other popular graphql client implementations such as …

Send `operationName` along with the `query` and `variables` by default

---

.changeset/rude-socks-doubt.md
packages/_scripts/build.js
packages/houdini-plugin-svelte-global-stores/package.json
packages/houdini-react/package.json
packages/houdini-svelte/package.json
packages/houdini/package.json

Fixes #1046
Include explicit `types` export conditions in
package.json `exports`.  The d.ts files are located elsewhere so can't relay on default value which is the same as the import, except with a `d.ts` extension.

Include explicit `types` export conditions in package.json `exports`

---

site/src/routes/intro/reusing-parts-of-a-query/+page.svx

Copying and pasting from the docs from [Reusing Parts of a Query](https://houdinigraphql.com/intro/reusing-parts-of-a-query) will produce the error:
```
❌ Encountered error in src/routes/[[id]]/+page.gql 
Syntax Error: Expected Name, found "=".
```
On the next section, [Mutations](https://houdinigraphql.com/intro/mutations), it reverts back to:
```diff
query Info($id: Int! = 1) {
species(id: $id) {
```
so I figured this must be a typo.

Docs: (TYPO) id number on wrong field

---

.changeset/mighty-rice-trade.md
packages/houdini-svelte/src/plugin/fsPatch.ts

Duplicate `+layout.js` files were being created in the root directory. This was an issue without side effects until sveltekit 1.15.5, which added a duplicate check. This fix allows houdini to work in sveltekit again.

fix: Duplicate virtual `+layout.js` files

---

.changeset/pink-coins-ring.md
packages/houdini-react/src/runtime/hooks/useDocumentHandle.ts
packages/houdini-react/src/runtime/hooks/useDocumentStore.ts
packages/houdini-react/src/runtime/hooks/useDocumentSubscription.ts
packages/houdini-react/src/runtime/hooks/useFragment.ts
packages/houdini-react/src/runtime/hooks/useFragmentHandle.ts
packages/houdini-react/src/runtime/hooks/useMutation.ts
packages/houdini-react/src/runtime/hooks/useQuery.ts
packages/houdini-react/src/runtime/hooks/useQueryHandle.ts
packages/houdini-react/src/runtime/hooks/useSubscription.ts
packages/houdini-react/src/runtime/hooks/useSubscriptionHandle.ts
packages/houdini-svelte/src/runtime/index.ts
packages/houdini-svelte/src/runtime/stores/base.ts
packages/houdini-svelte/src/runtime/stores/fragment.ts
packages/houdini-svelte/src/runtime/stores/mutation.ts
packages/houdini-svelte/src/runtime/stores/pagination/fragment.ts
packages/houdini-svelte/src/runtime/stores/pagination/query.ts
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini-svelte/src/runtime/stores/subscription.ts
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/stuff.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/index.ts
packages/houdini/src/runtime/lib/pagination.ts
packages/houdini/src/runtime/lib/types.ts

Fixes #1056.
This PR introduces `GraphQLVariables` type and unify type signatures of GraphQL input variables usages.
This PR is ready for review.

Improve GraphQL input typings

---

packages/houdini/src/lib/parse.ts

add missing jsx preset to parseJS

---

.changeset/chilled-planes-design.md
.changeset/pre.json
packages/houdini/src/codegen/validators/typeCheck.test.ts
packages/houdini/src/codegen/validators/typeCheck.ts

This PR adds a check in the document validation to ensure that `@loading` isn't applied on a floating fragment spread

Disallow floating fragment loading directive

---

.changeset/old-months-draw.md
packages/houdini-react/src/plugin/extract.ts
packages/houdini/src/lib/parse.ts

Fixes the issue found on discord [here](https://discord.com/channels/1024421016405016718/1099067986083594300)

Only parse as JSX in react bindings

---

.changeset/twelve-ravens-shout.md
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/stores/component_no_load_no_setup/+page.svelte
e2e/kit/src/routes/stores/component_no_load_no_setup/spec.ts
packages/houdini-svelte/src/plugin/artifactData.test.ts
packages/houdini-svelte/src/plugin/artifactData.ts
packages/houdini-svelte/src/runtime/stores/base.ts
packages/houdini-svelte/src/runtime/stores/query.ts

Fixes #1066 
This PR fixes an issue with lazy component queries. They were incorrectly subscribing to the cache before they were fetched.

Don't run setup on queries without load

---

e2e/_api/graphql.mjs
e2e/_api/schema.graphql
e2e/kit/src/app.html
e2e/kit/src/routes/+layout.svelte
e2e/kit/src/routes/stores/mutation-enums/+page.svelte
e2e/kit/src/routes/stores/mutation-opti-list/+page.svelte
e2e/kit/src/routes/stores/mutation-opti-list/spec.ts
e2e/kit/src/routes/stores/nested-list/+page.svelte
e2e/kit/src/routes/stores/nested-list/MUTATION.DeleteBook.gql
e2e/kit/src/routes/stores/nested-list/MUTATION.RemoveBook.gql
e2e/next/app/layout.tsx
e2e/react-vite/index.html
e2e/svelte/index.html
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/storage.ts
packages/houdini/src/runtime/cache/tests/subscriptions.test.ts
packages/houdini/src/runtime/client/plugins/mutation.ts

Clearing a layer notifies subscribers

---

packages/houdini-react/src/plugin/codegen/entries.test.ts
packages/houdini-react/src/plugin/codegen/manifest.test.ts
packages/houdini-react/src/plugin/codegen/manifest.ts
packages/houdini-react/src/plugin/codegen/router.test.ts
packages/houdini-react/src/plugin/conventions.ts

This PR adds support for route groups in the react router. For the most part, this didn't really require any changes except to the logic for generating page ids

Add route groups to react router

---

.changeset/two-vans-drive.md
packages/houdini/src/lib/config.test.ts
packages/houdini/src/lib/config.ts

Fixes [#discord](https://discord.com/channels/1024421016405016718/1111684053880553482/1111780792033628170)
---
FYI @Lms24
- This PR is to remove `?sentry-auto-wrap`
- Also, just to confirm, `houdini` needs to come before `sentrySvelteKit` in the vite config (to transform file)

filepath ignoring QueryString

---

.changeset/few-chicken-sell.md
packages/houdini/src/lib/parse.test.ts
packages/houdini/src/lib/parse.ts

I have a project where I have `experimentalDecorators: true` with a few decorators in some `ts` files.
Adding the 'decorators' plugin into the parseJS fix the issue.

Decorators are allowed in the project

---

site/src/routes/api/query/+page.svx

I couldn't remember if `fetching` or `loading` was the current way to check if a query is loading and I couldn't remember if that var exists on the store or on the store value. I went to the [API query docs](https://houdinigraphql.com/api/query)... and they confused me more :)  So I went to the type definition and source code and I think I was able to get it straightened out. Suggesting some updates to that page of the docs:
Here's the current docs on the query store fields:
https://github.com/HoudiniGraphql/houdini/blob/8bba6c3/site/src/routes/api/query/%2Bpage.svx#L91-L94
Here's the current type definition. I think `loading` was replaced by `fetching` a while ago. `variables` seems useful.
https://github.com/HoudiniGraphql/houdini/blob/8bba6c3/packages/houdini/src/runtime/lib/types.ts#L2 …

Refresh query result API docs

---

.changeset/serious-lobsters-smell.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/tests/subscriptions.test.ts

Fixes https://discord.com/channels/1024421016405016718/1114030809985327104 
This PR fixes an issue when writing a list over a previously null value

fix issue when writing list over null

---

.changeset/dull-hairs-confess.md
packages/houdini-svelte/src/runtime/index.ts

Resolves an issue where `QueryStoreFetchParams` cannot be imported from `$houdini`, meaning that generated operation files do not type-check their variables or event inputs.

Include types in houdini-svelte/runtime import (resolves QueryStoreFetchParams import failures)

---

.changeset/silver-fans-speak.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/tests/readwrite.test.ts

Fixes an issue reported in discord where someone needed a type to always be emebeded but couldn't use `[]` to do that.

Users can configure a type to always be embedded by setting keys to []

---

packages/houdini-svelte/src/plugin/index.ts

I stumbled upon some outdated documentation on the `@load` directive, and updated it to reflect its actual behavior.
Let me know if the updated comment is clear, or if it needs some more clarification.

Fix comment on `@load` directive

---

site/src/routes/api/query/+page.svx

Fixed old link to svelte docs load function args

Docs: Update url to Svelte docs in Hooks section

---

.changeset/red-feet-study.md
e2e/kit/src/routes/cache/+page.svelte
packages/houdini/src/runtime/public/types.ts

Fixes #1129 
The type definition of QueryInput used QueryValue, which resulted into it becoming `MyQuery$result`, instead of the expected `MyQuery$input`.
I'm not 100% sure how to write a proper test for this, suggestions welcome 🙂

Fix cache read and write input param types being generated incorrectly

---

.changeset/small-pets-draw.md
e2e/kit/src/lib/QueryComponent.svelte
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/plugin/query/component-in-route/+page.gql
e2e/kit/src/routes/plugin/query/component-in-route/+page.svelte
e2e/kit/src/routes/plugin/query/component-in-route/UserDetails.svelte
e2e/kit/src/routes/plugin/query/component-in-route/spec.ts
packages/houdini-svelte/src/plugin/codegen/components/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
packages/houdini-svelte/src/plugin/kit.ts

Fixes #1131 
Types for component queries inside of the routes didn't get types generated properly. See issue for full explanation.

Fix typegen for component queries inside of a route

---

packages/houdini/src/codegen/validators/typeCheck.ts

In case there's more than one fragment in a file, it can get tricky to identify which fragment is giving errors, so I added the name of the fragment to the error message to help figure out which one is causing issues.

Add fragment name to missing fragment arguments error

---

.changeset/mean-bikes-allow.md
packages/houdini/src/codegen/generators/artifacts/index.ts
packages/houdini/src/codegen/generators/artifacts/selection.ts
packages/houdini/src/codegen/generators/artifacts/utils.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/test/index.ts

Fixes #1165 
This PR fixes a bug when fragment variables were set to structured elements

Fix bug when structured values are used for fragment variables 

---

.changeset/large-donuts-melt.md
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/codegen/transforms/paginate.ts
packages/houdini/src/codegen/validators/typeCheck.ts

Enable custom arg to the node interface. (like `nodeId`)

Enable custom arg to the node interface.

---

.changeset/polite-apricots-grab.md
packages/houdini/src/codegen/generators/artifacts/utils.test.ts
packages/houdini/src/codegen/generators/artifacts/utils.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.ts

Fixes #1192 
This PR fixes a problem introduced in https://github.com/HoudiniGraphql/houdini/commit/41e3bdbf9a1bcc029fb8ef56fe91f7116a42a3b1#diff-8983c33c5d66912d4d0a408268e26c6d0b7242f4fd40a291ff5ee4121689dbb7 that was causing keys to be dropped from the artifact

Remove loc key from with arguments

---

.changeset/soft-toes-learn.md
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/stores/ssr-loadall-store-without-variables/+page.svelte
e2e/kit/src/routes/stores/ssr-loadall-store-without-variables/+page.ts
e2e/kit/src/routes/stores/ssr-loadall-store-without-variables/spec.ts
packages/houdini-svelte/src/runtime/index.ts

Fixes #1208
This PR fixes the typings of the `loadAll()` function.

Fix typings of `loadAll()` function

---

.changeset/three-comics-greet.md
packages/houdini/src/runtime/cache/subscription.ts

Fixes (can make an issue if needed)
Improves the performance of the functions related to cache subscriptions. Profiling with a large table for a work project resulted in roughly 50% less CPU time (the table uses many subscriptions, this made it go from ~500ms to ~220ms). Most of the improvement comes from line 156, replacing the `map()` and `includes()` with `some()`.

Optimize cache subscriptions

---

.changeset/neat-cameras-pay.md
e2e/_api/graphql.mjs
e2e/_api/schema.graphql
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/pagination/fragment/required-arguments/+page.svelte
e2e/kit/src/routes/pagination/fragment/required-arguments/spec.ts
packages/houdini-svelte/src/plugin/artifactData.test.ts
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini/src/codegen/generators/artifacts/inputs.ts
packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/pagination.test.ts
packages/houdini/src/codegen/generators/typescript/typescript.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.ts
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/codegen/transforms/paginate.ts
packages/houdini/src/codegen/validators/typeCheck.test.ts
packages/houdini/src/codegen/validators/typeCheck.ts
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/tests/variables.test.ts
packages/houdini/src/runtime/lib/types.ts
packages/houdini/src/test/index.ts

Fixes #1143
This PR adds functionality to allow required arguments inside paginated fragments.
I'll leave this PR as draft while I test it more thoroughly in our app for work, to make sure nothing else accidentally got broken :)

Allow for required arguments on paginated fragments

---

.changeset/tall-clocks-march.md
packages/houdini/package.json
pnpm-lock.yaml

Fixes #1256 
This PR bumps the version of babel's parser that we use internally which seems to have fixed the support for the `export type * from` expression

bump babel-parser version

---

.changeset/four-cobras-peel.md
e2e/kit/src/lib/utils/testsHelper.ts
packages/houdini-svelte/package.json
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini/src/codegen/generators/definitions/schema.test.ts
packages/houdini/src/codegen/transforms/schema.ts
packages/houdini/src/runtime/client/documentStore.ts
packages/houdini/src/runtime/client/plugins/cache.test.ts
packages/houdini/src/runtime/client/plugins/cache.ts
packages/houdini/src/runtime/lib/types.ts
pnpm-lock.yaml
site/src/routes/guides/caching-data/+page.svx

Fixes #356
Implement the policy "NoCache", mirroring Apollo, which serves a request without reading from or writing to the cache.
Tests are failing for me locally with messages like this:
```
TypeError: Cannot read properties of undefined (reading 'on')
❯ vitest.setup.ts:12:1
10| process.env.HOUDINI_TEST = 'true'
11| 
12| beforeEach(clearMock)
| ^
13| 
14| const config = testConfig()
```
This happens even without my changes, but it means I'm not able to write tests for the change.
~~- [ ] If applicable, add a test that would fail without this fix
~~- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [X ] Includes a changeset if your fix affects the user with `pnpm changeset`

Implement cache policy "NoCache"

---

.changeset/clever-pugs-switch.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/tests/list.test.ts

Fixes n/a
This PR adds support for using `@Foo_delete` on non-string values

Non string delete

---

.changeset/great-shrimps-admire.md
packages/houdini-react/src/runtime/routing/Router.tsx

This PR causes the react router to throw errors as exceptions when they are encountered in a query response. Since the component with the prop does the store, error boundaries compose into layouts naturally.

Improve error reporting in react bindings

---

.changeset/perfect-bags-occur.md
packages/houdini-svelte/src/plugin/extract.test.ts
packages/houdini-svelte/src/plugin/extract.ts

Otherwise it will fail to parse the source if the generics attribute contains angle brackets.
For example this code failed to parse:
```html
<script lang="ts" generics="T extends Record<string, unknown>">
</script>
```
Now the `parseSvelte` function will remove the generics attribute before calling the svelte preprocessor
preserving the token positions in the source code.
The output for the above example will be:
```html
<script lang="ts"                                             >
</script>
```

remove generics from script tag before calling svelte preprocessor

---

.changeset/big-pianos-pull.md
packages/houdini/src/cmd/init.ts

Fixes https://discord.com/channels/1024421016405016718/1214698361106472981
The old import was no longer supported since SvelteKit 2.

Fix vitePreprocess import in init script

---

.changeset/rotten-cobras-grin.md
e2e/kit/src/lib/utils/routes.ts
e2e/kit/src/routes/lists/mutation-insert/+page.gql
e2e/kit/src/routes/lists/mutation-insert/+page.svelte
e2e/kit/src/routes/lists/mutation-insert/+page.ts
e2e/kit/src/routes/lists/mutation-insert/spec.ts
packages/houdini/src/codegen/generators/artifacts/operations.ts
packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts

Fixes #1288
In the case of doing a `...MyList_insert @with(some: "param")`, the artifact generator that detects mutation list operations ran after the fragment spread hashing step, causing
`...MyList_insert @with(some: "param")`
to be transformed into
`...MyList_insert_asdf`
The code that tries to detect list operations works by checking if the fragment spread name ends with `_insert` or the like. Since we have the hash here at the end, this code would result in the code thinking this was not a list operation fragment.

Fix mutation list operations not working when passing `@with` directive

---

.changeset/early-masks-compete.md
packages/houdini/src/lib/parse.ts

Resolves #1287
Context : 
The following error message appears when trying to use the new javascript `using` keyword (https://github.com/tc39/proposal-explicit-resource-management)
```
$ vite dev
:x: Encountered error in src/routes/sverdle/+page.server.ts
This experimental syntax requires enabling the parser plugin: "explicitResourceManagement". (14:1)
error when starting dev server:
undefined
```
Typescript >5.2 [support](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management
) this out of the box, and there's a [babel plugin](https://babeljs.io/docs/babel-plugin-proposal-explicit-resource-management) that can be leveraged to support this.
I've tested the changes with a pnpm patch on a new sveltekit project and …

feat: add using keyword support

---

.changeset/afraid-pillows-worry.md
packages/houdini-svelte/src/plugin/fsPatch.ts

Fixes #1292 
So it turns out that `fs.statSync` takes in a `string | Buffer | URL` as path - the last of which does not have a `.includes()` function. (https://nodejs.org/docs/v20.11.1/api/fs.html#fsstatsyncpath-options)
Occasionally it is passed an `URL`, which then causes an error which bubbles up and causes the svelte LSP to crash. This PR fixes the fsPatch `statSync` function to properly handle this.

Fix houdini-svelte crashing the Svelte LSP

---

.changeset/breezy-waves-cover.md
.github/workflows/canary.yml
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/subscription.ts
packages/houdini/src/runtime/cache/tests/subscriptions.test.ts

This PR fixes a memory leak in the cache that was found as part of the investigation into #1294. This PR does not fix the original issue since it requires some additional thinking and there is a work-around

Fix memory leak in error path

---

site/src/routes/api/graphql-magic/+page.svx

I noticed that the API docs didn't mention the `@paginate` directive's "mode" parameter at all, so I added a bit of documentation.

Add PaginateMode to the paginate api docs

---

site/src/components/Toolbar.svelte

Previously the preferences such as language and theme were stored as session cookies, which means they got cleared whenever the browser shut down. Adding the max-age makes sure that they stay if you close the browser.

Persist docs preference cookies across browser sessions

---

.changeset/lemon-zebras-collect.md
packages/houdini/src/vite/houdini.ts

Fixes #1306 
Since the `addWatchFile` is context-aware, it ended up being invalid by the time the houdini plugins came around to use the function.
This PR is a quick fix to ensure that people can keep using Houdini with the latest version of Vite.
We'll need to properly rewrite the Vite plugin at one point so that `this.addWatchFile` is only called from within the houdini vite plugin itself.
For more context, take a look at the referenced issue, or [this thread](https://discord.com/channels/1024421016405016718/1254666346852126720) in Discord

Fix watchFiles error with vite 5.3

---

.changeset/funny-dogs-collect.md
packages/houdini/src/cmd/index.ts
packages/houdini/src/cmd/pullSchema.ts

Fixes #1115
This PR adds the `-o` flag to `pull-schema` which allows users to specify the output path for the schema

Allow users to specify the path when pulling their schema

---

.changeset/dirty-flies-matter.md
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/tests/scalars.test.ts
packages/houdini/src/runtime/lib/scalars.test.ts
packages/houdini/src/runtime/lib/scalars.ts

Fixes #1321
The marshalling step already had an extra check to marshal the individual values if it encountered an array. The unmarshalling step, however, was not invited to the party and just passed the raw values from the cache to the unmarshalling handler in the config.
Now the unmarshalling step has been invited and will pass the individual values of arrays to the proper `unmarshall` handler in the user's config.

Handle unmarshalling lists of custom scalars from the cache

---

.changeset/fifty-llamas-cry.md
packages/houdini-svelte/src/plugin/artifactData.test.ts
packages/houdini/src/codegen/generators/artifacts/index.ts
packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/loadingState.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/pagination.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/plugins.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/policy.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/selection.test.ts
packages/houdini/src/codegen/generators/typescript/documentTypes.test.ts
packages/houdini/src/codegen/generators/typescript/loadingState.test.ts
packages/houdini/src/codegen/generators/typescript/typescript.test.ts
packages/houdini/src/codegen/transforms/fragmentVariables.test.ts
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/runtime/client/plugins/fetchParams.ts
packages/houdini/src/runtime/client/plugins/optimisticKeys.test.ts
packages/houdini/src/runtime/client/plugins/test.ts
packages/houdini/src/runtime/lib/types.ts
packages/houdini/src/runtime/public/tests/test.ts

Fixes https://discord.com/channels/1024421016405016718/1268152875914104853
This PR fixes an issue when using the `@parentID` directive powered by a query variable. Before the variable would be sent along with the query (even tho it wasn't actually used). In some server runtimes, this causes an error.

Strip unused variables on their way out

---

.changeset/eighty-fishes-shake.md
packages/houdini-svelte/src/plugin/fsPatch.ts

When calculating a string filepath, use `URL.pathname` rather than `.toString()` if the given object is a URL.
Also pass the given filepath argument through to the underlying fs functions rather than using our generated string filepath.
These resolve an issue where `.toString()` on a URL returns a string prefixed with 'file://' even on POSIX devices, which cannot be used by the nodejs runtime bundled with Electron.
Fixes #1326

Fix arguments to patched filesystem functions

---

.changeset/swift-panthers-hug.md
e2e/react/package.json
e2e/react/src/routes/optimistic-keys/test.ts
packages/houdini-react/src/runtime/hooks/useFragment.ts
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/storage.ts
packages/houdini/src/runtime/cache/subscription.ts
packages/houdini/src/runtime/cache/tests/list.test.ts
packages/houdini/src/runtime/cache/tests/storage.test.ts
packages/houdini/src/runtime/cache/tests/subscriptions.test.ts
packages/houdini/src/runtime/client/plugins/optimisticKeys.ts

While building a trellix clone for Houdini, I ran into a few bugs related to some edge cases with our optimistic infrastructure. This PR will clean up what I run into while building the demo. So far, I have:
- fixed a bug when there are multiple pending optimistic inserts that rely on @optimisticKey
- addressed an issue when unsubscribes from a delete would be a little too aggressive
- fixed a bug when there is both a delete and create+insert that are optimistically pending

Optimistic key mutations

---

site/src/routes/guides/authentication/+page.svx

Hi! I spent way too much time trying to figure out why "Houdini isn't passing cookies to the API while Svelte is", after switching to OAuth2-backed authentication with HTTP-Only cookies.
This is just a friendly reminder, not something Houdini-specific, but it'll surely prevent some tickets ^^

Mention include: "credentials" in authentification docs

---

.changeset/thirty-melons-hug.md
.github/workflows/tests.yml
packages/_scripts/build.js
packages/houdini/src/cmd/init.ts

When running `npx houdini init` on a brand new svelte project, the init script would incorrectly assume the version for the `houdini` package is the same as the version for the `houdini-svelte` package.
This PR fixes it by altering the build script to fetch the package.json files for all the packages, and then either use `houdini`'s version, or `houdini-svelte`'s version

Fix init script using incorrect houdini-svelte version

---

.changeset/nasty-rats-obey.md
packages/houdini/src/lib/config.ts
packages/houdini/src/lib/introspection.ts

Fixes #1381 
Adds support for `*.graphqls` files in tooling.

Support '.graphqls' file extension

---

.github/workflows/tests.yml

This fixes currently broken builds, because of the deprecated CLI options in the svelte cli.
I also pinned the version of the cli to the current latest, 0.6, so that we don't have to do this again every time they push a non-backwards compatible change.

Update verify_init script to support changed sv CLI options

---

.changeset/cyan-steaks-laugh.md
packages/houdini/src/lib/config.ts

Fixes #1377
By just logging the error to the console instead of letting the exception bubble all the way up, we prevent vite from dying and thus forcing a full devserver manual restart when e.g. the graphql schema temporarily becomes invalid syntax. Useful when hand-writing the schema (with schema-first server development approaches) or even in code-first setups, when the tooling is such that the generated schema temporarily becomes a blank file somehow (totally not what is happening too me)
It looks like this on my end:
```bash
⚠️  Your schema file could not be loaded: Syntax Error: Unexpected <EOF>.
GraphQL request:1:1
1 |
| ^
❌ Cannot read properties of undefined (reading 'getDirectives')
3:55:04 AM [vite] page reload $houdini/runtime/index.js
3:55:04 AM [vite] page reload …
```

Don't crash dev server when a schema loading error occurs

---

site/src/routes/api/graphql-magic/+page.svx

This is just an update to a spelling error in the docs. No tests need to run and there is no change in the API that would require generateing a changeset.
These aren't applicable in this case
~- [ ] Update the first line to point to the ticket that this PR fixes~
~- [ ] Add a message that clearly describes the fix~
~- [ ] If applicable, add a test that would fail without this fix~
~- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`~
~- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`~

Fix documentation parameter type spelling error

---

.changeset/spicy-masks-care.md
.gitignore
.npmrc
e2e/kit/.gitignore
e2e/kit/houdini.config.js
e2e/kit/svelte.config.js
e2e/kit/tsconfig.json
e2e/kit/vite.config.js
package.json
packages/adapter-static/src/index.ts
packages/houdini-react/src/plugin/codegen/typeRoot.ts
packages/houdini-react/src/plugin/vite.tsx
packages/houdini-svelte/src/plugin/codegen/components/index.ts
packages/houdini-svelte/src/plugin/fsPatch.ts
packages/houdini/src/cmd/init.ts
packages/houdini/src/lib/config.ts
packages/houdini/src/lib/router/types.ts
packages/houdini/src/runtime/lib/config.ts
pnpm-lock.yaml
site/src/routes/api/config/+page.svx
site/src/routes/guides/contributing/+page.svx
tsconfig.json

Fixes #391 
This PR adds a config value to configure the output directory name for Houdini's generated files (`$houdini`) by default.

Allow changing the Houdini generated output directory

---

site/src/routes/guides/authentication/+page.svx

The property is called `credentials` and the value `include`. This only touches documentation so no tests have been changed.
Fixes #TICKET

Fix credentials key, value order

---

site/src/routes/guides/svelte-5/+page.svx

I initially didn't think that the $derived would be necessary, since the graphql tags return a store, but it ends up being very important so that if they are ever reassigned with a new store, the UI updates accordingly.
I also improved the wording a little bit and added the exact versions from which Svelte 5 is supported.

Improve svelte 5 documentation

---

.changeset/fluffy-lamps-provide.md
packages/houdini/src/runtime/client/plugins/fetch.ts

Fixes # N/A : https://discord.com/channels/1024421016405016718/1301635915663278131
Without this, if the server returns a non-JSON error response such as an NGINX error page, `defaultFetch` will still attempt to parse the response as JSON, which will throw a syntax error. Instead, this PR changes it to throw the semantic HTTP error which is easier to understand than a SyntaxError from parsing HTML as JSON.

Give better error when receiving non-JSON response

---

.changeset/happy-items-smell.md
e2e/kit/package.json
package.json
packages/houdini-react/package.json
packages/houdini-svelte/package.json
packages/houdini/package.json
pnpm-lock.yaml

Fixes #1401 
This upgrades the vite dependency to v6.
I haven't added a changelog yet as I'm not entirely sure how exactly we want to version this.
Leaving it as draft until we can figure this out. Can also change it to merge into the `houdini-2.0` branch...

Upgrade to vite 6

---

.changeset/fluffy-lamps-provide.md
.changeset/tough-insects-joke.md
packages/houdini/src/runtime/client/plugins/fetch.ts

Fixes # N/A
This PR fixes a bug from https://github.com/HoudiniGraphql/houdini/pull/1404 where valid `content-type`s would be treated as invalid because it checked that the `content-type` was strictly equal to one of the valid values. However, the `content-type` header can have other stuff in it after the content type, (e.g. `application/json; charset=utf-8`) so just check that it starts with the right thing instead of checking equality.

Fix bug where JSON error response might get treated as non-JSON error response

---

.changeset/big-queens-shop.md
.changeset/clean-weeks-fry.md
.changeset/grumpy-comics-talk.md
.changeset/lazy-seas-kick.md
.changeset/lemon-clouds-taste.md
.changeset/mighty-trains-switch.md
e2e/_api/graphql.mjs
e2e/_api/schema.graphql
e2e/react/src/routes/route_params/test.ts
e2e/react/src/routes/route_params_with_space/[title]/+page.gql
e2e/react/src/routes/route_params_with_space/[title]/+page.tsx
e2e/react/src/routes/route_params_with_space/[title]/test.ts
e2e/react/src/utils/routes.ts
packages/adapter-static/src/index.ts
packages/houdini-svelte/src/plugin/transforms/kit/session.test.ts
packages/houdini-svelte/src/plugin/transforms/kit/session.ts
packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/pagination.test.ts
packages/houdini/src/codegen/generators/artifacts/tests/selection.test.ts
packages/houdini/src/codegen/transforms/lists.test.ts
packages/houdini/src/codegen/transforms/paginate.test.ts
packages/houdini/src/codegen/transforms/paginate.ts
packages/houdini/src/runtime/cache/cache.ts
packages/houdini/src/runtime/cache/lists.ts
packages/houdini/src/runtime/cache/tests/list.test.ts
packages/houdini/src/runtime/router/match.test.ts
packages/houdini/src/runtime/router/match.ts
packages/houdini/src/vite/ast.ts

This PR fixes a few minor bugs:
- In react, if a url parameter was URI encoded, the encoded value was being passed as a variable. It's now decoded correctly
- If 2 operations that references the same field on a parent, the operation was happening twice. For example, if a field was tagged with 2 different `@lists` and both were included to ensure the mutation had the necessary fields for both, the value was inserted twice. 
- If a `@list` tagged field contained sublists, we wouldn't include `pageInfo` in the operation fragments which was causing an issue when reading the values back.
- If an exported load function was just the result of a function call (or a straight reference) it wasn't wrapped correctly

A small set of bug fixes

---

.changeset/rotten-baboons-invite.md
.github/workflows/tests.yml
e2e/react/package.json
package.json
packages/_scripts/build.js
packages/_scripts/package.json
packages/_scripts/typedefs.js
packages/adapter-static/package.json
packages/create-houdini/templates/react-typescript/package.json
packages/houdini-react/package.json
packages/houdini-react/src/runtime/routing/Router.tsx
packages/houdini/package.json
packages/houdini/src/lib/fs.ts
packages/houdini/src/runtime/router/types.ts
pnpm-lock.yaml

Fixes #1360 
This PR bumps the version of `glob`

Glob version

---

.changeset/tender-sloths-shave.md
packages/houdini-svelte/src/plugin/fsPatch.ts

Fixes #1401 
This PR fixes an issue with the svelte plugin that was breaking imports in vite 6. I'm still unsure if this is the right approach so i'm waiting to hear back from someone who knows better but I wanted to open this up for others to test.

fix import path resolution issue

---

.changeset/tender-cows-unite.md
packages/houdini-react/src/runtime/hooks/useMutation.ts
packages/houdini-svelte/src/runtime/stores/mutation.ts
packages/houdini-svelte/src/runtime/stores/query.ts
packages/houdini-svelte/src/runtime/types.ts
packages/houdini/src/runtime/lib/types.ts

This PR adds an `abortController` argument to query and mutation stores in svelte in order to abort the operation

add abortController to query and mutation args

---

.changeset/new-planets-sing.md
packages/adapter-static/package.json
packages/houdini-svelte/package.json
packages/houdini/package.json
packages/plugin-svelte-global-stores/package.json
pnpm-lock.yaml

This PR bumps the peerdependency versions of vite and sveltekit, as we apparently seem to have missed these between the peerdependencies and vite 6 PRs.

Fix peerdependencies versions

---

site/src/routes/api/config/+page.svx

I noticed that the `runtimeDir` option was incorrectly placed in the Svelte plugin section, while in reality the option lives in the config root.

Place runtimeDir documentation in the proper section

---

.changeset/sweet-dragons-brake.md
packages/houdini/src/cmd/init.ts

Fixes #1432
Using recast, this now updates the necessary fields instead of naively overwriting the entire config file.
This will make it easier for people who are migrating an existing app to Houdini.

Rework init script to only update the necessary fields in config files

---

site/src/routes/guides/loading-states/+page.svx

Fix file name typo in loading states docs

---

.changeset/forty-pandas-notice.md
packages/houdini/src/runtime/client/plugins/subscription.ts

Fixes typescript errors when using `graphql-sse` for the subscriptions client, as the types between `graphql-ws` and `graphql-sse` don't quite match 100%:
https://github.com/enisdenjo/graphql-ws/blob/5161bd91388677893badb8dbaca5c6587095199b/src/common.ts#L130-L135
https://github.com/enisdenjo/graphql-sse/blob/b8c6beb00dcd5ffc83c4bc64d50c73dd3869cf8e/src/common.ts#L37-L42

Subscription client types

---

.changeset/shiny-dogs-swim.md
packages/houdini/src/lib/config.test.ts
packages/houdini/src/lib/config.ts

Fixes #1444 
The exclude glob wasn't properly converted to an absolute path, so a file like `/path/to/project/src/exclude_me/hello.js` wasn't being caught by `src/exclude_me/**`.

Fix config exclude not matching absolute paths

---

site/plugins/docs-lang.js
site/plugins/docs-lang.test.js

Fixes #1438  
This PR fixes the JSDoc generation in the typescript transform funtion for all code examples on the website.

Fix: make sure TS transforms to JSdoc 💱

---

.changeset/shiny-kangaroos-cheat.md
packages/houdini-svelte/src/plugin/transforms/kit/init.test.ts
packages/houdini-svelte/src/plugin/transforms/kit/init.ts
packages/houdini-svelte/src/plugin/transforms/kit/load.test.ts
packages/houdini-svelte/src/plugin/transforms/kit/session.test.ts
packages/houdini/src/vite/imports.ts

Fixes #1462 
This PR updates the root layout transform so that the page stores we rely on are imported as a namespace to avoid a conflict if the user imports `page` from `$app/state`.

Avoid page state conflict

---

.changeset/orange-apricots-kiss.md
packages/houdini-svelte/src/plugin/transforms/componentQuery.test.ts
packages/houdini-svelte/src/plugin/transforms/componentQuery.ts

Fixes #1468
The generated load functions for component queries were not taking renamed props into account in Svelte 5, and ignoring them completely in legacy svelte mode. This PR fixes this bug.

Fix @load directive not using renamed props

---

.changeset/purple-readers-punch.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts

[houdini-svelte] properly warn against using page/layout queries when not include-ing .js files in houdini.config.js

---

.changeset/small-rice-remember.md
packages/houdini/src/cmd/init.ts
packages/houdini/src/lib/config.ts
packages/houdini/src/lib/introspection.ts
packages/houdini/src/runtime/lib/config.ts
packages/houdini/src/vite/schema.ts
site/src/routes/api/config/+page.svx

Fixes #1483
Implement schema poll without writing to disk.
Gracefully error out of schema write, since that's not technically required for houdini codegen.
By extension, allows glob local schemaPath & api poll (wathSchema) at the same time.

Feat config writepulledschema

---

.changeset/rare-poets-walk.md
packages/houdini/src/codegen/generators/indexFile/index.ts
packages/houdini/src/codegen/generators/runtime/pluginRuntime.ts
packages/houdini/src/codegen/index.ts
packages/houdini/src/lib/config.ts

This PR adds back the ability for plugins to include a static runtime that will be considered for document collection to the `houdini-2.0` branch

Static runtimes 2.0

---

.changeset/rare-poets-walk.md
packages/houdini/src/codegen/generators/indexFile/index.ts
packages/houdini/src/codegen/generators/runtime/pluginRuntime.ts
packages/houdini/src/codegen/index.ts
packages/houdini/src/lib/config.ts

This PR adds back the ability for plugins to include a static runtime that will be considered for document collection to the

Static runtimes

---

.changeset/mighty-games-happen.md
packages/houdini-svelte/src/plugin/codegen/routes/index.ts
packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
packages/houdini-svelte/src/runtime/types.ts

When trying to get a route's parent data in an automatic load function, the typings for the `event` parameter are handled incorrectly, losing type information vs the manual sveltekit load function:
Before the fix:
And after the fix:

Fix incorrect typings for automatic load event parameter

---

packages/houdini/src/cmd/init.ts
site/src/routes/api/config/+page.svx
site/src/routes/guides/release-notes/+page.svx

Fixes #1488 
Updated examples in documentation to use `Authorization` header (standard) instead of `Authentication` (non-standard).

Documentation: Fixed HTTP header in config examples

---

.changeset/afraid-poets-move.md
e2e/kit/package.json
packages/houdini-svelte/package.json
packages/houdini/src/cmd/init.ts
packages/plugin-svelte-global-stores/package.json
pnpm-lock.yaml
site/package.json

This PR constrains the maximum version of valid kit versions when working with the current branch of Houdini. Unfortunately version 2.21.1 introduced a breaking change for the magic that powers `+page.gql` files. As much as it saddens me, I think we have to move away from that API in sveltekit projects for the foreseeable future until kit gives us a first-class ability to add routes dynmically. 
Also, the recent RFC for async support also seems to indicate that the Svelte team is moving in a direction more in line with NextJS. I think this is ultimately a good move for the ecosystem but it doesn't mesh well with the `+page.gql` style of loaders. In this new world, `houdini-svelte` will likely only be responsible for generating the stores and letting users decide how they want to invoke …

Constrain maximum version of kit

---

.changeset/many-plants-dance.md
packages/houdini/src/runtime/cache/cache.ts

This PR fixes an issue that was causing values that were inserted from an operation to be written back to the cache in a subsequent pagination request causing them to appear twice.

Ensure values from paginated requests don't duplicate an operation insert

---

.changeset/breezy-geese-occur.md
packages/houdini/src/cmd/init.ts
packages/houdini/src/vite/houdini.ts
site/src/components/VersionNotice.svelte
site/src/layouts/_page.svelte

This adds a couple of notices that redirect users to houdini@next, since houdini 1.0 currently doesn't have support for the latest svelte-kit versions.
note: we should undo this PR once we finalize 2.0
what it looks like:

Add notices to redirect users to houdini@next
